-- ============================================
-- CREATE DATABASE AND SCHEMAS FOR SALES PLATFORM
-- ============================================

-- Create main sales database
CREATE OR REPLACE DATABASE SALES_DB
    DATA_RETENTION_TIME_IN_DAYS = 90  -- Keep data for 90 days
    MAX_DATA_EXTENSION_TIME_IN_DAYS = 14  -- Allow up to 14 days extension
    COMMENT = 'Main database for Real-Time Sales Platform';

-- Switch to the new database
USE DATABASE SALES_DB;

-- ============================================
-- CREATE SCHEMAS FOR DIFFERENT DATA LAYERS
-- ============================================

-- RAW schema for landing raw data
CREATE OR REPLACE SCHEMA RAW
    DATA_RETENTION_TIME_IN_DAYS = 30
    COMMENT = 'Raw data landing zone from S3/Kinesis';

-- STAGING schema for transformed data
CREATE OR REPLACE SCHEMA STAGING
    DATA_RETENTION_TIME_IN_DAYS = 60
    COMMENT = 'Staging area for transformed/cleaned data';

-- ANALYTICS schema for business-friendly tables
CREATE OR REPLACE SCHEMA ANALYTICS
    DATA_RETENTION_TIME_IN_DAYS = 90
    COMMENT = 'Analytics-ready tables with business logic';

-- AI schema for ML/AI results
CREATE OR REPLACE SCHEMA AI_RESULTS
    DATA_RETENTION_TIME_IN_DAYS = 180
    COMMENT = 'Storage for AI/ML model results and predictions';

-- MART schema for aggregated data marts
CREATE OR REPLACE SCHEMA DATA_MART
    DATA_RETENTION_TIME_IN_DAYS = 365  -- Keep mart data longer
    COMMENT = 'Aggregated data marts for specific business areas';

-- UTILS schema for helper functions and procedures
CREATE OR REPLACE SCHEMA UTILS
    DATA_RETENTION_TIME_IN_DAYS = 90
    COMMENT = 'Utility functions, stored procedures, and shared logic';

-- AUDIT schema for logging and monitoring
CREATE OR REPLACE SCHEMA AUDIT
    DATA_RETENTION_TIME_IN_DAYS = 180
    COMMENT = 'Audit logs, ETL tracking, and system metadata';

-- ============================================
-- SET UP FILE FORMATS FOR DATA LOADING
-- ============================================

-- JSON file format for raw data
CREATE OR REPLACE FILE FORMAT RAW.JSON_FORMAT
    TYPE = 'JSON'
    COMPRESSION = 'AUTO'
    STRIP_OUTER_ARRAY = TRUE
    STRIP_NULL_VALUES = TRUE
    IGNORE_UTF8_ERRORS = TRUE
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
    COMMENT = 'JSON file format for raw data ingestion';

-- CSV file format for structured data
CREATE OR REPLACE FILE FORMAT RAW.CSV_FORMAT
    TYPE = 'CSV'
    COMPRESSION = 'AUTO'
    FIELD_DELIMITER = ','
    RECORD_DELIMITER = '\n'
    SKIP_HEADER = 1
    DATE_FORMAT = 'AUTO'
    TIME_FORMAT = 'AUTO'
    TIMESTAMP_FORMAT = 'AUTO'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('NULL', 'null', '')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE
    COMMENT = 'CSV file format for structured data';

-- Parquet file format for optimized storage
CREATE OR REPLACE FILE FORMAT RAW.PARQUET_FORMAT
    TYPE = 'PARQUET'
    COMPRESSION = 'AUTO'
    COMMENT = 'Parquet file format for optimized columnar storage';

-- ============================================
-- CREATE EXTERNAL STAGES FOR DATA INGESTION
-- ============================================

-- Stage for S3 raw data
CREATE OR REPLACE STAGE RAW.S3_SALES_RAW_STAGE
    URL = 's3://sales-platform-raw-data-dev/kinesis/'
    STORAGE_INTEGRATION = AWS_S3_INTEGRATION
    FILE_FORMAT = RAW.JSON_FORMAT
    COMMENT = 'External stage for raw sales data from S3';

-- Stage for S3 processed data
CREATE OR REPLACE STAGE RAW.S3_SALES_PROCESSED_STAGE
    URL = 's3://sales-platform-processed-data-dev/'
    STORAGE_INTEGRATION = AWS_S3_INTEGRATION
    FILE_FORMAT = RAW.CSV_FORMAT
    COMMENT = 'External stage for processed sales data from S3';

-- Internal stage for manual uploads
CREATE OR REPLACE STAGE RAW.INTERNAL_STAGE
    FILE_FORMAT = RAW.CSV_FORMAT
    COMMENT = 'Internal stage for manual data uploads';

-- ============================================
-- SET UP SEQUENCES FOR SURROGATE KEYS
-- ============================================

CREATE OR REPLACE SEQUENCE ANALYTICS.DIM_CUSTOMER_SEQ
    START = 1
    INCREMENT = 1
    COMMENT = 'Sequence for CUSTOMER_DIM surrogate keys';

CREATE OR REPLACE SEQUENCE ANALYTICS.DIM_PRODUCT_SEQ
    START = 1
    INCREMENT = 1
    COMMENT = 'Sequence for PRODUCT_DIM surrogate keys';

CREATE OR REPLACE SEQUENCE ANALYTICS.DIM_DATE_SEQ
    START = 1
    INCREMENT = 1
    COMMENT = 'Sequence for DATE_DIM surrogate keys';

CREATE OR REPLACE SEQUENCE ANALYTICS.FACT_SALES_SEQ
    START = 1
    INCREMENT = 1
    COMMENT = 'Sequence for SALES_FACT surrogate keys';

-- ============================================
-- GRANT PERMISSIONS TO ROLES
-- ============================================

-- Grant database usage
GRANT USAGE ON DATABASE SALES_DB TO ROLE SALES_ADMIN;
GRANT USAGE ON DATABASE SALES_DB TO ROLE SALES_DEVELOPER;
GRANT USAGE ON DATABASE SALES_DB TO ROLE SALES_ANALYST;
GRANT USAGE ON DATABASE SALES_DB TO ROLE SALES_READ_ONLY;

-- Grant schema permissions
GRANT ALL PRIVILEGES ON SCHEMA RAW TO ROLE SALES_ADMIN;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA RAW TO ROLE SALES_DEVELOPER;
GRANT USAGE ON SCHEMA RAW TO ROLE SALES_ANALYST;
GRANT USAGE ON SCHEMA RAW TO ROLE SALES_READ_ONLY;

GRANT ALL PRIVILEGES ON SCHEMA STAGING TO ROLE SALES_ADMIN;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA STAGING TO ROLE SALES_DEVELOPER;
GRANT USAGE ON SCHEMA STAGING TO ROLE SALES_ANALYST;
GRANT USAGE ON SCHEMA STAGING TO ROLE SALES_READ_ONLY;

GRANT ALL PRIVILEGES ON SCHEMA ANALYTICS TO ROLE SALES_ADMIN;
GRANT USAGE, CREATE TABLE, CREATE VIEW ON SCHEMA ANALYTICS TO ROLE SALES_DEVELOPER;
GRANT USAGE, SELECT ON SCHEMA ANALYTICS TO ROLE SALES_ANALYST;
GRANT SELECT ON SCHEMA ANALYTICS TO ROLE SALES_READ_ONLY;

GRANT ALL PRIVILEGES ON SCHEMA AI_RESULTS TO ROLE SALES_ADMIN;
GRANT USAGE, CREATE TABLE ON SCHEMA AI_RESULTS TO ROLE SALES_DEVELOPER;
GRANT USAGE, SELECT ON SCHEMA AI_RESULTS TO ROLE SALES_ANALYST;
GRANT SELECT ON SCHEMA AI_RESULTS TO ROLE SALES_READ_ONLY;

GRANT ALL PRIVILEGES ON SCHEMA DATA_MART TO ROLE SALES_ADMIN;
GRANT USAGE, CREATE VIEW ON SCHEMA DATA_MART TO ROLE SALES_DEVELOPER;
GRANT USAGE, SELECT ON SCHEMA DATA_MART TO ROLE SALES_ANALYST;
GRANT SELECT ON SCHEMA DATA_MART TO ROLE SALES_READ_ONLY;

GRANT ALL PRIVILEGES ON SCHEMA UTILS TO ROLE SALES_ADMIN;
GRANT USAGE, CREATE FUNCTION, CREATE PROCEDURE ON SCHEMA UTILS TO ROLE SALES_DEVELOPER;
GRANT USAGE ON SCHEMA UTILS TO ROLE SALES_ANALYST;

GRANT ALL PRIVILEGES ON SCHEMA AUDIT TO ROLE SALES_ADMIN;
GRANT USAGE, CREATE TABLE ON SCHEMA AUDIT TO ROLE SALES_DEVELOPER;
GRANT USAGE ON SCHEMA AUDIT TO ROLE SALES_ANALYST;

-- Grant file format permissions
GRANT USAGE ON FILE FORMAT RAW.JSON_FORMAT TO ROLE SALES_DEVELOPER;
GRANT USAGE ON FILE FORMAT RAW.CSV_FORMAT TO ROLE SALES_DEVELOPER;
GRANT USAGE ON FILE FORMAT RAW.PARQUET_FORMAT TO ROLE SALES_DEVELOPER;

-- Grant stage permissions
GRANT USAGE ON STAGE RAW.S3_SALES_RAW_STAGE TO ROLE SALES_DEVELOPER;
GRANT USAGE ON STAGE RAW.S3_SALES_PROCESSED_STAGE TO ROLE SALES_DEVELOPER;
GRANT READ ON STAGE RAW.INTERNAL_STAGE TO ROLE SALES_DEVELOPER;

-- Grant sequence permissions
GRANT USAGE ON SEQUENCE ANALYTICS.DIM_CUSTOMER_SEQ TO ROLE SALES_DEVELOPER;
GRANT USAGE ON SEQUENCE ANALYTICS.DIM_PRODUCT_SEQ TO ROLE SALES_DEVELOPER;
GRANT USAGE ON SEQUENCE ANALYTICS.DIM_DATE_SEQ TO ROLE SALES_DEVELOPER;
GRANT USAGE ON SEQUENCE ANALYTICS.FACT_SALES_SEQ TO ROLE SALES_DEVELOPER;

-- ============================================
-- CREATE AUDIT LOGGING TABLE
-- ============================================

CREATE OR REPLACE TABLE AUDIT.ETL_LOGS (
    LOG_ID NUMBER AUTOINCREMENT,
    PROCESS_NAME VARCHAR(100),
    SCHEMA_NAME VARCHAR(50),
    TABLE_NAME VARCHAR(100),
    RECORDS_PROCESSED NUMBER,
    START_TIME TIMESTAMP_NTZ,
    END_TIME TIMESTAMP_NTZ,
    STATUS VARCHAR(20),
    ERROR_MESSAGE VARCHAR(1000),
    DURATION_SECONDS NUMBER AS (DATEDIFF(SECOND, START_TIME, END_TIME)),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (PROCESS_NAME, START_TIME)
COMMENT = 'Audit logs for ETL processes';

-- Create view for monitoring ETL performance
CREATE OR REPLACE VIEW AUDIT.VW_ETL_PERFORMANCE AS
SELECT
    PROCESS_NAME,
    DATE_TRUNC('DAY', START_TIME) AS PROCESS_DATE,
    COUNT(*) AS RUN_COUNT,
    AVG(RECORDS_PROCESSED) AS AVG_RECORDS_PROCESSED,
    AVG(DURATION_SECONDS) AS AVG_DURATION_SECONDS,
    SUM(CASE WHEN STATUS = 'SUCCESS' THEN 1 ELSE 0 END) AS SUCCESS_COUNT,
    SUM(CASE WHEN STATUS = 'FAILED' THEN 1 ELSE 0 END) AS FAILED_COUNT
FROM AUDIT.ETL_LOGS
GROUP BY PROCESS_NAME, DATE_TRUNC('DAY', START_TIME)
ORDER BY PROCESS_DATE DESC;

-- ============================================
-- DATABASE SETUP SUMMARY
-- ============================================

-- Show created schemas
SELECT
    SCHEMA_NAME,
    CREATED,
    LAST_ALTERED,
    COMMENT
FROM INFORMATION_SCHEMA.SCHEMATA
WHERE CATALOG_NAME = 'SALES_DB'
ORDER BY SCHEMA_NAME;

-- Show file formats
SELECT
    FILE_FORMAT_NAME,
    FORMAT_TYPE,
    CREATED,
    COMMENT
FROM INFORMATION_SCHEMA.FILE_FORMATS
WHERE FILE_FORMAT_SCHEMA = 'RAW';

-- Show stages
SELECT
    STAGE_NAME,
    STAGE_URL,
    STAGE_TYPE,
    CREATED,
    COMMENT
FROM INFORMATION_SCHEMA.STAGES
WHERE STAGE_SCHEMA = 'RAW';

SELECT
    'DATABASE SETUP COMPLETE' AS STATUS,
    'Run create_tables.sql next to create fact and dimension tables' AS NEXT_STEP;