-- ============================================
-- ANALYTICAL VIEWS FOR BUSINESS INTELLIGENCE
-- ============================================

-- ============================================
-- SALES PERFORMANCE VIEWS
-- ============================================

-- Daily Sales Summary View
CREATE OR REPLACE VIEW ANALYTICS.VW_DAILY_SALES_SUMMARY AS
SELECT
    d.DATE,
    d.YEAR,
    d.MONTH,
    d.MONTH_NAME,
    d.DAY_NAME,
    d.IS_WEEKEND,
    d.SEASON,
    COUNT(DISTINCT fs.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
    COUNT(DISTINCT fs.CUSTOMER_SK) AS UNIQUE_CUSTOMERS,
    SUM(fs.QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(fs.LINE_FINAL_AMOUNT) AS TOTAL_SALES,
    SUM(fs.LINE_COST_AMOUNT) AS TOTAL_COST,
    SUM(fs.LINE_PROFIT_AMOUNT) AS TOTAL_PROFIT,
    AVG(fs.LINE_PROFIT_MARGIN) AS AVG_PROFIT_MARGIN,
    SUM(fs.LINE_DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT,
    COUNT(DISTINCT fs.PRODUCT_SK) AS UNIQUE_PRODUCTS_SOLD,
    SUM(CASE WHEN fs.FRAUD_DETECTED THEN fs.LINE_FINAL_AMOUNT ELSE 0 END) AS FRAUD_AMOUNT,
    SUM(CASE WHEN fs.FRAUD_DETECTED THEN 1 ELSE 0 END) AS FRAUD_TRANSACTIONS
FROM ANALYTICS.FACT_SALES fs
JOIN ANALYTICS.DIM_DATE d ON fs.DATE_KEY = d.DATE_KEY
GROUP BY d.DATE, d.YEAR, d.MONTH, d.MONTH_NAME, d.DAY_NAME, d.IS_WEEKEND, d.SEASON
ORDER BY d.DATE DESC;

-- Monthly Sales Trend View
CREATE OR REPLACE VIEW ANALYTICS.VW_MONTHLY_SALES_TREND AS
SELECT
    d.YEAR,
    d.MONTH,
    d.MONTH_NAME,
    COUNT(DISTINCT fs.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
    COUNT(DISTINCT fs.CUSTOMER_SK) AS UNIQUE_CUSTOMERS,
    SUM(fs.QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(fs.LINE_FINAL_AMOUNT) AS TOTAL_SALES,
    SUM(fs.LINE_PROFIT_AMOUNT) AS TOTAL_PROFIT,
    AVG(fs.LINE_PROFIT_MARGIN) AS AVG_PROFIT_MARGIN,
    LAG(SUM(fs.LINE_FINAL_AMOUNT), 1) OVER (ORDER BY d.YEAR, d.MONTH) AS PREV_MONTH_SALES,
    SUM(fs.LINE_FINAL_AMOUNT) - LAG(SUM(fs.LINE_FINAL_AMOUNT), 1) OVER (ORDER BY d.YEAR, d.MONTH) AS SALES_GROWTH,
    CASE 
        WHEN LAG(SUM(fs.LINE_FINAL_AMOUNT), 1) OVER (ORDER BY d.YEAR, d.MONTH) > 0 
        THEN ((SUM(fs.LINE_FINAL_AMOUNT) - LAG(SUM(fs.LINE_FINAL_AMOUNT), 1) OVER (ORDER BY d.YEAR, d.MONTH)) / 
              LAG(SUM(fs.LINE_FINAL_AMOUNT), 1) OVER (ORDER BY d.YEAR, d.MONTH)) * 100 
        ELSE NULL 
    END AS SALES_GROWTH_PERCENT
FROM ANALYTICS.FACT_SALES fs
JOIN ANALYTICS.DIM_DATE d ON fs.DATE_KEY = d.DATE_KEY
GROUP BY d.YEAR, d.MONTH, d.MONTH_NAME
ORDER BY d.YEAR DESC, d.MONTH DESC;

-- Hourly Sales Pattern View
CREATE OR REPLACE VIEW ANALYTICS.VW_HOURLY_SALES_PATTERN AS
SELECT
    t.HOUR,
    t.TIME_PERIOD,
    t.IS_BUSINESS_HOURS,
    t.IS_PEAK_HOURS,
    COUNT(DISTINCT fs.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
    SUM(fs.LINE_FINAL_AMOUNT) AS TOTAL_SALES,
    AVG(fs.LINE_FINAL_AMOUNT) AS AVG_TRANSACTION_VALUE,
    COUNT(DISTINCT fs.CUSTOMER_SK) AS UNIQUE_CUSTOMERS,
    SUM(fs.QUANTITY) AS TOTAL_QUANTITY_SOLD
FROM ANALYTICS.FACT_SALES fs
JOIN ANALYTICS.DIM_TIME t ON fs.TIME_KEY = t.TIME_KEY
GROUP BY t.HOUR, t.TIME_PERIOD, t.IS_BUSINESS_HOURS, t.IS_PEAK_HOURS
ORDER BY t.HOUR;

-- ============================================
-- CUSTOMER ANALYTICS VIEWS
-- ============================================

-- Customer Lifetime Value View
CREATE OR REPLACE VIEW ANALYTICS.VW_CUSTOMER_LIFETIME_VALUE AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.CUSTOMER_SEGMENT,
    c.CUSTOMER_TIER,
    c.RFM_SEGMENT,
    c.REGION,
    c.AGE_GROUP,
    COUNT(DISTINCT fs.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
    SUM(fs.QUANTITY) AS TOTAL_QUANTITY_PURCHASED,
    SUM(fs.LINE_FINAL_AMOUNT) AS TOTAL_SPENT,
    AVG(fs.LINE_FINAL_AMOUNT) AS AVG_TRANSACTION_VALUE,
    MIN(fs.TRANSACTION_TIMESTAMP) AS FIRST_PURCHASE_DATE,
    MAX(fs.TRANSACTION_TIMESTAMP) AS LAST_PURCHASE_DATE,
    DATEDIFF('day', MIN(fs.TRANSACTION_TIMESTAMP), MAX(fs.TRANSACTION_TIMESTAMP)) AS CUSTOMER_LIFETIME_DAYS,
    CASE 
        WHEN DATEDIFF('day', MIN(fs.TRANSACTION_TIMESTAMP), MAX(fs.TRANSACTION_TIMESTAMP)) > 0 
        THEN SUM(fs.LINE_FINAL_AMOUNT) / DATEDIFF('day', MIN(fs.TRANSACTION_TIMESTAMP), MAX(fs.TRANSACTION_TIMESTAMP)) 
        ELSE SUM(fs.LINE_FINAL_AMOUNT) 
    END AS DAILY_SPENDING_RATE,
    CASE 
        WHEN COUNT(DISTINCT fs.TRANSACTION_ID) > 1 
        THEN DATEDIFF('day', MIN(fs.TRANSACTION_TIMESTAMP), MAX(fs.TRANSACTION_TIMESTAMP)) / (COUNT(DISTINCT fs.TRANSACTION_ID) - 1) 
        ELSE NULL 
    END AS AVG_PURCHASE_FREQUENCY_DAYS
FROM ANALYTICS.FACT_SALES fs
JOIN ANALYTICS.DIM_CUSTOMER c ON fs.CUSTOMER_SK = c.CUSTOMER_SK AND c.IS_CURRENT = TRUE
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME, c.CUSTOMER_SEGMENT, c.CUSTOMER_TIER, c.RFM_SEGMENT, c.REGION, c.AGE_GROUP
ORDER BY TOTAL_SPENT DESC;

-- Customer Segmentation Analysis View
CREATE OR REPLACE VIEW ANALYTICS.VW_CUSTOMER_SEGMENT_ANALYSIS AS
SELECT
    c.CUSTOMER_SEGMENT,
    c.CUSTOMER_TIER,
    c.RFM_SEGMENT,
    COUNT(DISTINCT c.CUSTOMER_ID) AS CUSTOMER_COUNT,
    SUM(fs.LINE_FINAL_AMOUNT) AS TOTAL_REVENUE,
    AVG(fs.LINE_FINAL_AMOUNT) AS AVG_REVENUE_PER_CUSTOMER,
    COUNT(DISTINCT fs.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
    AVG(fs.QUANTITY) AS AVG_ITEMS_PER_TRANSACTION,
    SUM(CASE WHEN fs.IS_FIRST_PURCHASE THEN 1 ELSE 0 END) AS NEW_CUSTOMERS,
    SUM(CASE WHEN fs.IS_REPEAT_PURCHASE THEN 1 ELSE 0 END) AS REPEAT_CUSTOMERS,
    AVG(fs.LINE_PROFIT_MARGIN) AS AVG_PROFIT_MARGIN,
    SUM(fs.LINE_DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT_GIVEN
FROM ANALYTICS.FACT_SALES fs
JOIN ANALYTICS.DIM_CUSTOMER c ON fs.CUSTOMER_SK = c.CUSTOMER_SK AND c.IS_CURRENT = TRUE
GROUP BY c.CUSTOMER_SEGMENT, c.CUSTOMER_TIER, c.RFM_SEGMENT
ORDER BY TOTAL_REVENUE DESC;

-- Customer Churn Risk View
CREATE OR REPLACE VIEW ANALYTICS.VW_CUSTOMER_CHURN_RISK AS
SELECT
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.RECENCY_SEGMENT,
    c.FREQUENCY_SEGMENT,
    c.VALUE_SEGMENT,
    c.RFM_SEGMENT,
    DATEDIFF('day', MAX(fs.TRANSACTION_TIMESTAMP), CURRENT_DATE()) AS DAYS_SINCE_LAST_PURCHASE,
    CASE
        WHEN DATEDIFF('day', MAX(fs.TRANSACTION_TIMESTAMP), CURRENT_DATE()) > 180 THEN 'HIGH'
        WHEN DATEDIFF('day', MAX(fs.TRANSACTION_TIMESTAMP), CURRENT_DATE()) > 90 THEN 'MEDIUM'
        WHEN DATEDIFF('day', MAX(fs.TRANSACTION_TIMESTAMP), CURRENT_DATE()) > 30 THEN 'LOW'
        ELSE 'ACTIVE'
    END AS CHURN_RISK_LEVEL,
    COUNT(DISTINCT fs.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
    SUM(fs.LINE_FINAL_AMOUNT) AS TOTAL_SPENT,
    MAX(fs.TRANSACTION_TIMESTAMP) AS LAST_PURCHASE_DATE
FROM ANALYTICS.FACT_SALES fs
JOIN ANALYTICS.DIM_CUSTOMER c ON fs.CUSTOMER_SK = c.CUSTOMER_SK AND c.IS_CURRENT = TRUE
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME, c.RECENCY_SEGMENT, c.FREQUENCY_SEGMENT, c.VALUE_SEGMENT, c.RFM_SEGMENT
HAVING DATEDIFF('day', MAX(fs.TRANSACTION_TIMESTAMP), CURRENT_DATE()) > 30
ORDER BY DAYS_SINCE_LAST_PURCHASE DESC, TOTAL_SPENT DESC;

-- ============================================
-- PRODUCT ANALYTICS VIEWS
-- ============================================

-- Product Performance View
CREATE OR REPLACE VIEW ANALYTICS.VW_PRODUCT_PERFORMANCE AS
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.SUBCATEGORY,
    p.BRAND,
    p.PRODUCT_LIFECYCLE_STAGE,
    p.PROFITABILITY_SEGMENT,
    p.STOCK_STATUS,
    COUNT(DISTINCT fs.TRANSACTION_ID) AS TIMES_SOLD,
    SUM(fs.QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(fs.LINE_FINAL_AMOUNT) AS TOTAL_REVENUE,
    SUM(fs.LINE_COST_AMOUNT) AS TOTAL_COST,
    SUM(fs.LINE_PROFIT_AMOUNT) AS TOTAL_PROFIT,
    AVG(fs.LINE_PROFIT_MARGIN) AS AVG_PROFIT_MARGIN,
    COUNT(DISTINCT fs.CUSTOMER_SK) AS UNIQUE_CUSTOMERS,
    AVG(fs.UNIT_PRICE) AS AVG_SELLING_PRICE,
    p.CURRENT_PRICE AS CURRENT_RETAIL_PRICE,
    CASE 
        WHEN SUM(fs.QUANTITY) > 0 
        THEN SUM(fs.LINE_FINAL_AMOUNT) / SUM(fs.QUANTITY) 
        ELSE 0 
    END AS AVG_REVENUE_PER_UNIT
FROM ANALYTICS.FACT_SALES fs
JOIN ANALYTICS.DIM_PRODUCT p ON fs.PRODUCT_SK = p.PRODUCT_SK AND p.IS_CURRENT = TRUE
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY, p.SUBCATEGORY, p.BRAND, 
         p.PRODUCT_LIFECYCLE_STAGE, p.PROFITABILITY_SEGMENT, p.STOCK_STATUS, p.CURRENT_PRICE
ORDER BY TOTAL_REVENUE DESC;

-- Category Performance View
CREATE OR REPLACE VIEW ANALYTICS.VW_CATEGORY_PERFORMANCE AS
SELECT
    p.CATEGORY,
    p.SUBCATEGORY,
    COUNT(DISTINCT p.PRODUCT_ID) AS TOTAL_PRODUCTS,
    COUNT(DISTINCT fs.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
    SUM(fs.QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(fs.LINE_FINAL_AMOUNT) AS TOTAL_REVENUE,
    SUM(fs.LINE_PROFIT_AMOUNT) AS TOTAL_PROFIT,
    AVG(fs.LINE_PROFIT_MARGIN) AS AVG_PROFIT_MARGIN,
    COUNT(DISTINCT fs.CUSTOMER_SK) AS UNIQUE_CUSTOMERS,
    SUM(fs.LINE_DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT,
    AVG(fs.UNIT_PRICE) AS AVG_PRICE_POINT
FROM ANALYTICS.FACT_SALES fs
JOIN ANALYTICS.DIM_PRODUCT p ON fs.PRODUCT_SK = p.PRODUCT_SK AND p.IS_CURRENT = TRUE
GROUP BY p.CATEGORY, p.SUBCATEGORY
ORDER BY TOTAL_REVENUE DESC;

-- Product Inventory Health View
CREATE OR REPLACE VIEW ANALYTICS.VW_PRODUCT_INVENTORY_HEALTH AS
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.CATEGORY,
    p.SUBCATEGORY,
    p.STOCK_QUANTITY,
    p.STOCK_STATUS,
    p.REORDER_LEVEL,
    COALESCE(SUM(fs.QUANTITY), 0) AS LAST_30_DAY_SALES,
    CASE 
        WHEN SUM(fs.QUANTITY) > 0 
        THEN p.STOCK_QUANTITY / (SUM(fs.QUANTITY) / 30.0) 
        ELSE NULL 
    END AS DAYS_OF_SUPPLY,
    CASE
        WHEN p.STOCK_STATUS = 'Out of Stock' THEN 'CRITICAL'
        WHEN p.STOCK_STATUS = 'Low Stock' THEN 'WARNING'
        WHEN DAYS_OF_SUPPLY < 7 THEN 'LOW_SUPPLY'
        WHEN DAYS_OF_SUPPLY > 90 THEN 'OVERSTOCKED'
        ELSE 'HEALTHY'
    END AS INVENTORY_HEALTH_STATUS,
    p.CURRENT_PRICE * p.STOCK_QUANTITY AS INVENTORY_VALUE
FROM ANALYTICS.DIM_PRODUCT p
LEFT JOIN ANALYTICS.FACT_SALES fs ON p.PRODUCT_SK = fs.PRODUCT_SK 
    AND fs.TRANSACTION_TIMESTAMP >= DATEADD('day', -30, CURRENT_DATE())
WHERE p.IS_CURRENT = TRUE
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME, p.CATEGORY, p.SUBCATEGORY, 
         p.STOCK_QUANTITY, p.STOCK_STATUS, p.REORDER_LEVEL, p.CURRENT_PRICE
ORDER BY INVENTORY_HEALTH_STATUS, DAYS_OF_SUPPLY;

-- ============================================
-- GEOGRAPHICAL ANALYTICS VIEWS
-- ============================================

-- Regional Sales Performance View
CREATE OR REPLACE VIEW ANALYTICS.VW_REGIONAL_SALES_PERFORMANCE AS
SELECT
    c.REGION,
    c.COUNTRY,
    c.STATE,
    c.CITY,
    COUNT(DISTINCT fs.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
    SUM(fs.QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(fs.LINE_FINAL_AMOUNT) AS TOTAL_REVENUE,
    SUM(fs.LINE_PROFIT_AMOUNT) AS TOTAL_PROFIT,
    AVG(fs.LINE_PROFIT_MARGIN) AS AVG_PROFIT_MARGIN,
    COUNT(DISTINCT fs.CUSTOMER_SK) AS UNIQUE_CUSTOMERS,
    AVG(fs.TRANSACTION_TOTAL) AS AVG_TRANSACTION_VALUE,
    SUM(fs.LINE_DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT_GIVEN
FROM ANALYTICS.FACT_SALES fs
JOIN ANALYTICS.DIM_CUSTOMER c ON fs.CUSTOMER_SK = c.CUSTOMER_SK AND c.IS_CURRENT = TRUE
GROUP BY c.REGION, c.COUNTRY, c.STATE, c.CITY
ORDER BY TOTAL_REVENUE DESC;

-- ============================================
-- MARKETING ANALYTICS VIEWS
-- ============================================

-- Campaign Performance View
CREATE OR REPLACE VIEW ANALYTICS.VW_CAMPAIGN_PERFORMANCE AS
SELECT
    cam.CAMPAIGN_NAME,
    cam.CAMPAIGN_TYPE,
    cam.CHANNEL,
    cam.STATUS,
    COUNT(DISTINCT fs.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
    SUM(fs.QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(fs.LINE_FINAL_AMOUNT) AS ATTRIBUTED_REVENUE,
    COUNT(DISTINCT fs.CUSTOMER_SK) AS UNIQUE_CUSTOMERS_ACQUIRED,
    SUM(CASE WHEN fs.IS_FIRST_PURCHASE THEN 1 ELSE 0 END) AS NEW_CUSTOMERS,
    AVG(fs.LINE_FINAL_AMOUNT) AS AVG_ORDER_VALUE,
    MIN(fs.TRANSACTION_TIMESTAMP) AS FIRST_CAMPAIGN_SALE,
    MAX(fs.TRANSACTION_TIMESTAMP) AS LAST_CAMPAIGN_SALE
FROM ANALYTICS.FACT_SALES fs
JOIN ANALYTICS.DIM_CAMPAIGN cam ON fs.CAMPAIGN_SK = cam.CAMPAIGN_SK AND cam.IS_CURRENT = TRUE
GROUP BY cam.CAMPAIGN_NAME, cam.CAMPAIGN_TYPE, cam.CHANNEL, cam.STATUS
ORDER BY ATTRIBUTED_REVENUE DESC;

-- ============================================
-- FINANCIAL ANALYTICS VIEWS
-- ============================================

-- Profitability Analysis View
CREATE OR REPLACE VIEW ANALYTICS.VW_PROFITABILITY_ANALYSIS AS
SELECT
    d.YEAR,
    d.MONTH,
    d.MONTH_NAME,
    p.CATEGORY,
    p.SUBCATEGORY,
    p.BRAND,
    c.CUSTOMER_SEGMENT,
    c.CUSTOMER_TIER,
    COUNT(DISTINCT fs.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
    SUM(fs.QUANTITY) AS TOTAL_QUANTITY_SOLD,
    SUM(fs.LINE_FINAL_AMOUNT) AS TOTAL_REVENUE,
    SUM(fs.LINE_COST_AMOUNT) AS TOTAL_COST,
    SUM(fs.LINE_PROFIT_AMOUNT) AS TOTAL_PROFIT,
    AVG(fs.LINE_PROFIT_MARGIN) AS AVG_PROFIT_MARGIN,
    SUM(fs.LINE_DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT,
    (SUM(fs.LINE_PROFIT_AMOUNT) / SUM(fs.LINE_FINAL_AMOUNT)) * 100 AS OVERALL_PROFIT_MARGIN_PERCENT
FROM ANALYTICS.FACT_SALES fs
JOIN ANALYTICS.DIM_DATE d ON fs.DATE_KEY = d.DATE_KEY
JOIN ANALYTICS.DIM_PRODUCT p ON fs.PRODUCT_SK = p.PRODUCT_SK AND p.IS_CURRENT = TRUE
JOIN ANALYTICS.DIM_CUSTOMER c ON fs.CUSTOMER_SK = c.CUSTOMER_SK AND c.IS_CURRENT = TRUE
GROUP BY d.YEAR, d.MONTH, d.MONTH_NAME, p.CATEGORY, p.SUBCATEGORY, p.BRAND, c.CUSTOMER_SEGMENT, c.CUSTOMER_TIER
ORDER BY d.YEAR DESC, d.MONTH DESC, TOTAL_PROFIT DESC;

-- ============================================
-- OPERATIONAL ANALYTICS VIEWS
-- ============================================

-- Fraud Detection Analysis View
CREATE OR REPLACE VIEW ANALYTICS.VW_FRAUD_DETECTION_ANALYSIS AS
SELECT
    DATE(fs.TRANSACTION_TIMESTAMP) AS TRANSACTION_DATE,
    pay.PAYMENT_METHOD,
    ch.CHANNEL_TYPE,
    COUNT(*) AS TOTAL_TRANSACTIONS,
    SUM(CASE WHEN fs.FRAUD_DETECTED THEN 1 ELSE 0 END) AS FRAUDULENT_TRANSACTIONS,
    SUM(CASE WHEN fs.FRAUD_DETECTED THEN fs.LINE_FINAL_AMOUNT ELSE 0 END) AS FRAUD_AMOUNT,
    CASE 
        WHEN COUNT(*) > 0 
        THEN SUM(CASE WHEN fs.FRAUD_DETECTED THEN 1 ELSE 0 END) * 100.0 / COUNT(*) 
        ELSE 0 
    END AS FRAUD_RATE_PERCENT,
    AVG(CASE WHEN fs.FRAUD_DETECTED THEN fs.FRAUD_SCORE ELSE NULL END) AS AVG_FRAUD_SCORE
FROM ANALYTICS.FACT_SALES fs
JOIN ANALYTICS.DIM_PAYMENT pay ON fs.PAYMENT_SK = pay.PAYMENT_SK
JOIN ANALYTICS.DIM_CHANNEL ch ON fs.CHANNEL_SK = ch.CHANNEL_SK
GROUP BY DATE(fs.TRANSACTION_TIMESTAMP), pay.PAYMENT_METHOD, ch.CHANNEL_TYPE
ORDER BY TRANSACTION_DATE DESC, FRAUD_RATE_PERCENT DESC;

-- ============================================
-- SUMMARY VIEWS FOR DASHBOARDS
-- ============================================

-- Executive Dashboard Summary View
CREATE OR REPLACE VIEW DATA_MART.VW_EXECUTIVE_DASHBOARD AS
SELECT
    'SALES' AS METRIC_CATEGORY,
    'Total Revenue' AS METRIC_NAME,
    SUM(LINE_FINAL_AMOUNT) AS METRIC_VALUE,
    'CURRENCY' AS METRIC_UNIT
FROM ANALYTICS.FACT_SALES
WHERE TRANSACTION_TIMESTAMP >= DATEADD('day', -30, CURRENT_DATE())
UNION ALL
SELECT
    'SALES',
    'Total Profit',
    SUM(LINE_PROFIT_AMOUNT),
    'CURRENCY'
FROM ANALYTICS.FACT_SALES
WHERE TRANSACTION_TIMESTAMP >= DATEADD('day', -30, CURRENT_DATE())
UNION ALL
SELECT
    'CUSTOMERS',
    'Total Customers',
    COUNT(DISTINCT CUSTOMER_SK),
    'COUNT'
FROM ANALYTICS.FACT_SALES
WHERE TRANSACTION_TIMESTAMP >= DATEADD('day', -30, CURRENT_DATE())
UNION ALL
SELECT
    'CUSTOMERS',
    'New Customers',
    SUM(CASE WHEN IS_FIRST_PURCHASE THEN 1 ELSE 0 END),
    'COUNT'
FROM ANALYTICS.FACT_SALES
WHERE TRANSACTION_TIMESTAMP >= DATEADD('day', -30, CURRENT_DATE())
UNION ALL
SELECT
    'PRODUCTS',
    'Products Sold',
    COUNT(DISTINCT PRODUCT_SK),
    'COUNT'
FROM ANALYTICS.FACT_SALES
WHERE TRANSACTION_TIMESTAMP >= DATEADD('day', -30, CURRENT_DATE())
UNION ALL
SELECT
    'OPERATIONS',
    'Transaction Volume',
    COUNT(*),
    'COUNT'
FROM ANALYTICS.FACT_SALES
WHERE TRANSACTION_TIMESTAMP >= DATEADD('day', -30, CURRENT_DATE());

-- ============================================
-- VIEW DEPENDENCIES AND METADATA
-- ============================================

-- View to show all created views with metadata
CREATE OR REPLACE VIEW UTILS.VW_VIEW_METADATA AS
SELECT
    TABLE_CATALOG AS DATABASE_NAME,
    TABLE_SCHEMA AS SCHEMA_NAME,
    TABLE_NAME AS VIEW_NAME,
    COMMENT AS VIEW_DESCRIPTION,
    CREATED,
    LAST_ALTERED
FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_CATALOG = 'SALES_DB'
ORDER BY TABLE_SCHEMA, TABLE_NAME;

-- ============================================
-- VIEW CREATION SUMMARY
-- ============================================

SELECT
    'ANALYTICAL VIEWS CREATED SUCCESSFULLY' AS STATUS,
    COUNT(*) AS VIEW_COUNT,
    STRING_AGG(TABLE_NAME, ', ') WITHIN GROUP (ORDER BY TABLE_NAME) AS VIEW_LIST
FROM INFORMATION_SCHEMA.VIEWS
WHERE TABLE_CATALOG = 'SALES_DB'
AND TABLE_SCHEMA IN ('ANALYTICS', 'DATA_MART', 'UTILS');