-- ============================================
-- COPY COMMANDS FOR DATA LOADING
-- ============================================

-- ============================================
-- LOAD RAW DATA FROM S3
-- ============================================

-- Load raw transactions from S3 JSON files
COPY INTO RAW.TRANSACTIONS_RAW
FROM @RAW.S3_SALES_RAW_STAGE
FILE_FORMAT = (FORMAT_NAME = 'RAW.JSON_FORMAT')
PATTERN = '.*\.json\.gz'
ON_ERROR = 'CONTINUE'
PURGE = FALSE
FORCE = FALSE
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- Load raw products from S3 (if available)
COPY INTO RAW.PRODUCTS_RAW
FROM @RAW.S3_SALES_PROCESSED_STAGE/products/
FILE_FORMAT = (FORMAT_NAME = 'RAW.JSON_FORMAT')
PATTERN = '.*\.json'
ON_ERROR = 'CONTINUE'
PURGE = FALSE;

-- Load raw customers from S3 (if available)
COPY INTO RAW.CUSTOMERS_RAW
FROM @RAW.S3_SALES_PROCESSED_STAGE/customers/
FILE_FORMAT = (FORMAT_NAME = 'RAW.JSON_FORMAT')
PATTERN = '.*\.json'
ON_ERROR = 'CONTINUE'
PURGE = FALSE;

-- ============================================
-- TRANSFORM AND LOAD STAGING TABLES
-- ============================================

-- Transform and load staging transactions
INSERT INTO STAGING.TRANSACTIONS (
    TRANSACTION_ID,
    ORDER_ID,
    TRANSACTION_TIMESTAMP,
    CUSTOMER_ID,
    STORE_ID,
    CAMPAIGN_ID,
    SALES_REP_ID,
    CHANNEL,
    DEVICE_TYPE,
    BROWSER,
    OS,
    IP_ADDRESS,
    SUBTOTAL_AMOUNT,
    DISCOUNT_AMOUNT,
    TAX_AMOUNT,
    SHIPPING_AMOUNT,
    TOTAL_AMOUNT,
    PAYMENT_METHOD,
    PAYMENT_STATUS,
    PAYMENT_ID,
    FRAUD_DETECTED,
    FRAUD_SCORE,
    CURRENCY,
    FULFILLMENT_STATUS,
    SHIPPING_METHOD,
    TRACKING_NUMBER,
    ESTIMATED_DELIVERY_DATE,
    SEASON,
    IS_WEEKEND,
    IS_HOLIDAY,
    BATCH_ID,
    IS_VALID,
    VALIDATION_ERRORS
)
SELECT
    RAW_DATA:transaction_id::STRING,
    RAW_DATA:order_id::STRING,
    RAW_DATA:timestamp::TIMESTAMP_NTZ,
    RAW_DATA:customer.customer_id::STRING,
    RAW_DATA:store.store_id::STRING,
    RAW_DATA:campaign.campaign_id::STRING,
    RAW_DATA:sales_rep.rep_id::STRING,
    RAW_DATA:channel::STRING,
    RAW_DATA:device::STRING,
    RAW_DATA:browser::STRING,
    RAW_DATA:operating_system::STRING,
    RAW_DATA:ip_address::STRING,
    RAW_DATA:financials.subtotal::FLOAT,
    RAW_DATA:financials.discounts.total_discount::FLOAT,
    RAW_DATA:financials.tax_amount::FLOAT,
    RAW_DATA:financials.shipping_cost::FLOAT,
    RAW_DATA:financials.total_amount::FLOAT,
    RAW_DATA:payment.method::STRING,
    RAW_DATA:payment.status::STRING,
    RAW_DATA:payment.payment_id::STRING,
    RAW_DATA:payment.fraud_detected::BOOLEAN,
    RAW_DATA:payment.fraud_score::INTEGER,
    RAW_DATA:financials.currency::STRING,
    RAW_DATA:fulfillment.status::STRING,
    RAW_DATA:financials.shipping_method::STRING,
    RAW_DATA:fulfillment.tracking_number::STRING,
    TRY_TO_DATE(RAW_DATA:fulfillment.estimated_delivery::STRING),
    RAW_DATA:metadata.season::STRING,
    RAW_DATA:metadata.is_weekend::BOOLEAN,
    RAW_DATA:metadata.is_holiday::BOOLEAN,
    'BATCH_' || CURRENT_DATE()::STRING,
    TRUE,
    NULL
FROM RAW.TRANSACTIONS_RAW
WHERE RAW_DATA:transaction_id IS NOT NULL
AND RAW_DATA:timestamp IS NOT NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY RAW_DATA:transaction_id::STRING 
    ORDER BY RAW_DATA:timestamp::TIMESTAMP_NTZ DESC
) = 1;

-- Transform and load staging transaction items
INSERT INTO STAGING.TRANSACTION_ITEMS (
    TRANSACTION_ID,
    PRODUCT_ID,
    QUANTITY,
    UNIT_PRICE,
    TOTAL_PRICE,
    DISCOUNT_PERCENTAGE,
    DISCOUNT_AMOUNT,
    TAX_AMOUNT,
    FINAL_PRICE,
    PRODUCT_CATEGORY,
    PRODUCT_SUBCATEGORY,
    PRODUCT_BRAND,
    PRODUCT_SKU
)
SELECT
    r.RAW_DATA:transaction_id::STRING,
    p.value:product_id::STRING,
    p.value:quantity::INTEGER,
    p.value:unit_price::FLOAT,
    p.value:total_price::FLOAT,
    CASE 
        WHEN p.value:total_price::FLOAT > 0 
        THEN (r.RAW_DATA:financials.discounts.total_discount::FLOAT / p.value:total_price::FLOAT) * 100 
        ELSE 0 
    END,
    (r.RAW_DATA:financials.discounts.total_discount::FLOAT / COUNT(*) OVER (PARTITION BY r.RAW_DATA:transaction_id)) * p.value:quantity::INTEGER,
    (r.RAW_DATA:financials.tax_amount::FLOAT / COUNT(*) OVER (PARTITION BY r.RAW_DATA:transaction_id)) * p.value:quantity::INTEGER,
    p.value:total_price::FLOAT,
    p.value:category::STRING,
    p.value:subcategory::STRING,
    p.value:brand::STRING,
    p.value:sku::STRING
FROM RAW.TRANSACTIONS_RAW r,
LATERAL FLATTEN(input => r.RAW_DATA:products) p
WHERE r.RAW_DATA:transaction_id IS NOT NULL
AND p.value:product_id IS NOT NULL;

-- Transform and load staging customers
INSERT INTO STAGING.CUSTOMERS (
    CUSTOMER_ID,
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER,
    DATE_OF_BIRTH,
    AGE,
    GENDER,
    INCOME_BRACKET,
    OCCUPATION,
    COMPANY,
    ADDRESS_STREET,
    ADDRESS_CITY,
    ADDRESS_STATE,
    ADDRESS_COUNTRY,
    ADDRESS_POSTAL_CODE,
    ADDRESS_REGION,
    ACCOUNT_CREATED_DATE,
    LAST_LOGIN_DATE,
    ACCOUNT_STATUS,
    CUSTOMER_SEGMENT,
    LIFETIME_VALUE,
    AVG_ORDER_VALUE,
    PURCHASE_FREQUENCY,
    LAST_PURCHASE_DATE,
    TOTAL_ORDERS,
    TOTAL_SPENT,
    PREFERRED_CHANNEL,
    PREFERRED_CATEGORY,
    LOYALTY_POINTS,
    NEWSLETTER_SUBSCRIBED,
    MARKETING_OPT_IN,
    CUSTOMER_TIER,
    CREDIT_SCORE,
    PREFERRED_PAYMENT_METHOD,
    SHIPPING_PREFERENCE,
    IS_ACTIVE
)
SELECT DISTINCT
    RAW_DATA:customer_id::STRING,
    RAW_DATA:first_name::STRING,
    RAW_DATA:last_name::STRING,
    RAW_DATA:email::STRING,
    RAW_DATA:phone::STRING,
    TRY_TO_DATE(RAW_DATA:date_of_birth::STRING),
    RAW_DATA:age::INTEGER,
    RAW_DATA:gender::STRING,
    RAW_DATA:income_bracket::STRING,
    RAW_DATA:occupation::STRING,
    RAW_DATA:company::STRING,
    RAW_DATA:address.street::STRING,
    RAW_DATA:address.city::STRING,
    RAW_DATA:address.state::STRING,
    RAW_DATA:address.country::STRING,
    RAW_DATA:address.postal_code::STRING,
    RAW_DATA:address.region::STRING,
    TRY_TO_DATE(RAW_DATA:account_created::STRING),
    TRY_TO_DATE(RAW_DATA:last_login::STRING),
    RAW_DATA:account_status::STRING,
    RAW_DATA:customer_segment::STRING,
    RAW_DATA:lifetime_value::FLOAT,
    RAW_DATA:avg_order_value::FLOAT,
    RAW_DATA:purchase_frequency::INTEGER,
    TRY_TO_DATE(RAW_DATA:last_purchase_date::STRING),
    RAW_DATA:total_orders::INTEGER,
    RAW_DATA:total_spent::FLOAT,
    RAW_DATA:preferred_channel::STRING,
    RAW_DATA:preferred_category::STRING,
    RAW_DATA:loyalty_points::INTEGER,
    RAW_DATA:newsletter_subscribed::BOOLEAN,
    RAW_DATA:marketing_opt_in::BOOLEAN,
    RAW_DATA:customer_tier::STRING,
    RAW_DATA:credit_score::INTEGER,
    RAW_DATA:preferred_payment_method::STRING,
    RAW_DATA:shipping_preference::STRING,
    RAW_DATA:account_status::STRING = 'Active'
FROM RAW.CUSTOMERS_RAW
WHERE RAW_DATA:customer_id IS NOT NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY RAW_DATA:customer_id::STRING 
    ORDER BY RAW_DATA:last_login::TIMESTAMP_NTZ DESC NULLS LAST
) = 1;

-- Transform and load staging products
INSERT INTO STAGING.PRODUCTS (
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    SUBCATEGORY,
    BRAND,
    SKU,
    PRICE,
    COST_PRICE,
    PROFIT_MARGIN,
    STOCK_QUANTITY,
    REORDER_LEVEL,
    SUPPLIER_ID,
    MANUFACTURER,
    WEIGHT_KG,
    DIMENSIONS,
    COLOR,
    MATERIAL,
    WARRANTY_MONTHS,
    RATING,
    REVIEWS_COUNT,
    IS_ACTIVE,
    DATE_ADDED,
    LAST_UPDATED,
    TAGS,
    DESCRIPTION,
    FEATURES,
    IS_SEASONAL,
    IS_LIMITED_EDITION,
    IS_BESTSELLER,
    IS_NEW_ARRIVAL
)
SELECT DISTINCT
    RAW_DATA:product_id::STRING,
    RAW_DATA:product_name::STRING,
    RAW_DATA:category::STRING,
    RAW_DATA:subcategory::STRING,
    RAW_DATA:brand::STRING,
    RAW_DATA:sku::STRING,
    RAW_DATA:price::FLOAT,
    RAW_DATA:cost_price::FLOAT,
    RAW_DATA:profit_margin::FLOAT,
    RAW_DATA:stock_quantity::INTEGER,
    RAW_DATA:reorder_level::INTEGER,
    RAW_DATA:supplier_id::STRING,
    RAW_DATA:manufacturer::STRING,
    RAW_DATA:weight_kg::FLOAT,
    RAW_DATA:dimensions::STRING,
    RAW_DATA:color::STRING,
    RAW_DATA:material::STRING,
    RAW_DATA:warranty_months::INTEGER,
    RAW_DATA:rating::FLOAT,
    RAW_DATA:reviews_count::INTEGER,
    RAW_DATA:is_active::BOOLEAN,
    TRY_TO_DATE(RAW_DATA:date_added::STRING),
    CURRENT_TIMESTAMP(),
    PARSE_JSON(RAW_DATA:tags::STRING),
    RAW_DATA:description::STRING,
    PARSE_JSON(RAW_DATA:features::STRING),
    RAW_DATA:metadata.seasonal::BOOLEAN,
    RAW_DATA:metadata.limited_edition::BOOLEAN,
    RAW_DATA:metadata.bestseller::BOOLEAN,
    RAW_DATA:metadata.new_arrival::BOOLEAN
FROM RAW.PRODUCTS_RAW
WHERE RAW_DATA:product_id IS NOT NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY RAW_DATA:product_id::STRING 
    ORDER BY TRY_TO_DATE(RAW_DATA:last_updated::STRING) DESC NULLS LAST
) = 1;

-- ============================================
-- LOAD DIMENSION TABLES
-- ============================================

-- Load Date Dimension (for a 10-year period)
INSERT INTO ANALYTICS.DIM_DATE
SELECT
    TO_NUMBER(TO_CHAR(DATE, 'YYYYMMDD')) AS DATE_KEY,
    DATE,
    YEAR(DATE) AS YEAR,
    QUARTER(DATE) AS QUARTER,
    MONTH(DATE) AS MONTH,
    MONTHNAME(DATE) AS MONTH_NAME,
    DAY(DATE) AS DAY_OF_MONTH,
    DAYOFWEEK(DATE) AS DAY_OF_WEEK,
    DAYNAME(DATE) AS DAY_NAME,
    WEEKOFYEAR(DATE) AS WEEK_OF_YEAR,
    DAYOFWEEK(DATE) IN (6, 7) AS IS_WEEKEND,
    FALSE AS IS_HOLIDAY, -- Would be populated from holiday calendar
    NULL AS HOLIDAY_NAME,
    YEAR(DATE) AS FISCAL_YEAR, -- Assuming calendar year fiscal
    QUARTER(DATE) AS FISCAL_QUARTER,
    MONTH(DATE) AS FISCAL_MONTH,
    CASE 
        WHEN MONTH(DATE) IN (12, 1, 2) THEN 'Winter'
        WHEN MONTH(DATE) IN (3, 4, 5) THEN 'Spring'
        WHEN MONTH(DATE) IN (6, 7, 8) THEN 'Summer'
        ELSE 'Fall'
    END AS SEASON
FROM (
    SELECT DATEADD(DAY, SEQ4(), '2020-01-01') AS DATE
    FROM TABLE(GENERATOR(ROWCOUNT => 3650)) -- 10 years
);

-- Load Time Dimension
INSERT INTO ANALYTICS.DIM_TIME
SELECT
    (HOUR * 100) + MINUTE AS TIME_KEY,
    HOUR,
    MINUTE,
    HOUR AS HOUR_OF_DAY,
    CASE
        WHEN HOUR BETWEEN 5 AND 11 THEN 'Morning'
        WHEN HOUR BETWEEN 12 AND 16 THEN 'Afternoon'
        WHEN HOUR BETWEEN 17 AND 21 THEN 'Evening'
        ELSE 'Night'
    END AS TIME_PERIOD,
    HOUR BETWEEN 9 AND 17 AS IS_BUSINESS_HOURS,
    HOUR IN (12, 13, 18, 19) AS IS_PEAK_HOURS,
    CURRENT_TIMESTAMP()
FROM (
    SELECT HOUR, MINUTE
    FROM (
        SELECT SEQ4() AS HOUR FROM TABLE(GENERATOR(ROWCOUNT => 24))
    ) HOURS
    CROSS JOIN (
        SELECT SEQ4() AS MINUTE FROM TABLE(GENERATOR(ROWCOUNT => 60))
    ) MINUTES
);

-- Load Customer Dimension (SCD Type 2)
INSERT INTO ANALYTICS.DIM_CUSTOMER (
    CUSTOMER_ID,
    CUSTOMER_NAME,
    EMAIL,
    PHONE_NUMBER,
    DATE_OF_BIRTH,
    AGE,
    AGE_GROUP,
    GENDER,
    INCOME_BRACKET,
    OCCUPATION,
    COMPANY,
    CITY,
    STATE,
    COUNTRY,
    REGION,
    POSTAL_CODE,
    ACCOUNT_CREATED_DATE,
    ACCOUNT_AGE_DAYS,
    ACCOUNT_STATUS,
    CUSTOMER_SEGMENT,
    CUSTOMER_TIER,
    LIFETIME_VALUE,
    VALUE_SEGMENT,
    PURCHASE_FREQUENCY,
    FREQUENCY_SEGMENT,
    RECENCY_DAYS,
    RECENCY_SEGMENT,
    RFM_SCORE,
    RFM_SEGMENT,
    PREFERRED_CHANNEL,
    PREFERRED_CATEGORY,
    LOYALTY_POINTS,
    NEWSLETTER_SUBSCRIBED,
    MARKETING_OPT_IN,
    CREDIT_SCORE,
    PREFERRED_PAYMENT_METHOD,
    SHIPPING_PREFERENCE,
    IS_ACTIVE,
    VALID_FROM
)
SELECT
    CUSTOMER_ID,
    FIRST_NAME || ' ' || LAST_NAME AS CUSTOMER_NAME,
    EMAIL,
    PHONE_NUMBER,
    DATE_OF_BIRTH,
    AGE,
    CASE
        WHEN AGE < 25 THEN '18-24'
        WHEN AGE < 35 THEN '25-34'
        WHEN AGE < 45 THEN '35-44'
        WHEN AGE < 55 THEN '45-54'
        WHEN AGE < 65 THEN '55-64'
        ELSE '65+'
    END AS AGE_GROUP,
    GENDER,
    INCOME_BRACKET,
    OCCUPATION,
    COMPANY,
    ADDRESS_CITY AS CITY,
    ADDRESS_STATE AS STATE,
    ADDRESS_COUNTRY AS COUNTRY,
    ADDRESS_REGION AS REGION,
    ADDRESS_POSTAL_CODE AS POSTAL_CODE,
    ACCOUNT_CREATED_DATE,
    DATEDIFF('day', ACCOUNT_CREATED_DATE, CURRENT_DATE()) AS ACCOUNT_AGE_DAYS,
    ACCOUNT_STATUS,
    CUSTOMER_SEGMENT,
    CUSTOMER_TIER,
    LIFETIME_VALUE,
    CASE
        WHEN LIFETIME_VALUE > 10000 THEN 'High'
        WHEN LIFETIME_VALUE > 1000 THEN 'Medium'
        ELSE 'Low'
    END AS VALUE_SEGMENT,
    PURCHASE_FREQUENCY,
    CASE
        WHEN PURCHASE_FREQUENCY > 24 THEN 'Frequent'
        WHEN PURCHASE_FREQUENCY > 12 THEN 'Regular'
        ELSE 'Occasional'
    END AS FREQUENCY_SEGMENT,
    DATEDIFF('day', LAST_PURCHASE_DATE, CURRENT_DATE()) AS RECENCY_DAYS,
    CASE
        WHEN RECENCY_DAYS <= 30 THEN 'Recent'
        WHEN RECENCY_DAYS <= 90 THEN 'Active'
        WHEN RECENCY_DAYS <= 180 THEN 'Lapsed'
        ELSE 'Churned'
    END AS RECENCY_SEGMENT,
    CASE
        WHEN VALUE_SEGMENT = 'High' THEN 3
        WHEN VALUE_SEGMENT = 'Medium' THEN 2
        ELSE 1
    END * 
    CASE
        WHEN FREQUENCY_SEGMENT = 'Frequent' THEN 3
        WHEN FREQUENCY_SEGMENT = 'Regular' THEN 2
        ELSE 1
    END * 
    CASE
        WHEN RECENCY_SEGMENT = 'Recent' THEN 3
        WHEN RECENCY_SEGMENT = 'Active' THEN 2
        ELSE 1
    END AS RFM_SCORE,
    CASE
        WHEN RFM_SCORE >= 27 THEN 'Champions'
        WHEN RFM_SCORE >= 18 THEN 'Loyal Customers'
        WHEN RFM_SCORE >= 12 THEN 'Potential Loyalists'
        WHEN RFM_SCORE >= 8 THEN 'Recent Customers'
        WHEN RFM_SCORE >= 4 THEN 'Promising'
        WHEN RFM_SCORE >= 2 THEN 'Needs Attention'
        ELSE 'At Risk'
    END AS RFM_SEGMENT,
    PREFERRED_CHANNEL,
    PREFERRED_CATEGORY,
    LOYALTY_POINTS,
    NEWSLETTER_SUBSCRIBED,
    MARKETING_OPT_IN,
    CREDIT_SCORE,
    PREFERRED_PAYMENT_METHOD,
    SHIPPING_PREFERENCE,
    IS_ACTIVE,
    CURRENT_TIMESTAMP() AS VALID_FROM
FROM STAGING.CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL;

-- Load Product Dimension (SCD Type 2)
INSERT INTO ANALYTICS.DIM_PRODUCT (
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    SUBCATEGORY,
    BRAND,
    SKU,
    CURRENT_PRICE,
    COST_PRICE,
    PROFIT_MARGIN_PERCENT,
    PROFITABILITY_SEGMENT,
    STOCK_QUANTITY,
    STOCK_STATUS,
    SUPPLIER_ID,
    MANUFACTURER,
    WEIGHT_KG,
    DIMENSIONS,
    COLOR,
    MATERIAL,
    WARRANTY_MONTHS,
    RATING,
    REVIEWS_COUNT,
    POPULARITY_SCORE,
    PRODUCT_LIFECYCLE_STAGE,
    IS_ACTIVE,
    IS_SEASONAL,
    IS_LIMITED_EDITION,
    IS_BESTSELLER,
    IS_NEW_ARRIVAL,
    DATE_ADDED,
    VALID_FROM
)
SELECT
    PRODUCT_ID,
    PRODUCT_NAME,
    CATEGORY,
    SUBCATEGORY,
    BRAND,
    SKU,
    PRICE,
    COST_PRICE,
    PROFIT_MARGIN,
    CASE
        WHEN PROFIT_MARGIN > 40 THEN 'High'
        WHEN PROFIT_MARGIN > 20 THEN 'Medium'
        ELSE 'Low'
    END AS PROFITABILITY_SEGMENT,
    STOCK_QUANTITY,
    CASE
        WHEN STOCK_QUANTITY = 0 THEN 'Out of Stock'
        WHEN STOCK_QUANTITY <= REORDER_LEVEL THEN 'Low Stock'
        ELSE 'In Stock'
    END AS STOCK_STATUS,
    SUPPLIER_ID,
    MANUFACTURER,
    WEIGHT_KG,
    DIMENSIONS,
    COLOR,
    MATERIAL,
    WARRANTY_MONTHS,
    RATING,
    REVIEWS_COUNT,
    CASE
        WHEN REVIEWS_COUNT > 1000 AND RATING > 4.5 THEN 10
        WHEN REVIEWS_COUNT > 500 AND RATING > 4.0 THEN 8
        WHEN REVIEWS_COUNT > 100 AND RATING > 3.5 THEN 6
        WHEN REVIEWS_COUNT > 10 THEN 4
        ELSE 2
    END AS POPULARITY_SCORE,
    CASE
        WHEN DATE_ADDED > DATEADD('month', -3, CURRENT_DATE()) THEN 'Introduction'
        WHEN DATE_ADDED > DATEADD('month', -12, CURRENT_DATE()) THEN 'Growth'
        WHEN DATE_ADDED > DATEADD('month', -24, CURRENT_DATE()) THEN 'Maturity'
        ELSE 'Decline'
    END AS PRODUCT_LIFECYCLE_STAGE,
    IS_ACTIVE,
    IS_SEASONAL,
    IS_LIMITED_EDITION,
    IS_BESTSELLER,
    IS_NEW_ARRIVAL,
    DATE_ADDED,
    CURRENT_TIMESTAMP() AS VALID_FROM
FROM STAGING.PRODUCTS
WHERE PRODUCT_ID IS NOT NULL;

-- Load Payment Dimension
INSERT INTO ANALYTICS.DIM_PAYMENT (
    PAYMENT_METHOD,
    PAYMENT_TYPE,
    PAYMENT_NETWORK,
    SECURITY_LEVEL,
    PROCESSING_FEE_PERCENT,
    AVERAGE_PROCESSING_TIME_SECONDS,
    SUCCESS_RATE_PERCENT,
    IS_DIGITAL,
    IS_INSTANT,
    SUPPORTED_COUNTRIES
)
VALUES
    ('Credit Card', 'Card', 'Visa', 'High', 2.5, 2, 98.5, TRUE, TRUE, ARRAY_CONSTRUCT('US', 'CA', 'UK', 'AU')),
    ('Debit Card', 'Card', 'Mastercard', 'High', 1.5, 1, 99.0, TRUE, TRUE, ARRAY_CONSTRUCT('US', 'CA', 'UK', 'AU')),
    ('PayPal', 'Digital Wallet', 'PayPal', 'High', 2.9, 3, 97.0, TRUE, TRUE, ARRAY_CONSTRUCT('US', 'CA', 'UK', 'AU', 'DE')),
    ('Apple Pay', 'Digital Wallet', 'Apple', 'High', 2.0, 1, 99.5, TRUE, TRUE, ARRAY_CONSTRUCT('US', 'CA', 'UK', 'AU')),
    ('Google Pay', 'Digital Wallet', 'Google', 'High', 2.0, 1, 99.0, TRUE, TRUE, ARRAY_CONSTRUCT('US', 'CA', 'UK', 'AU')),
    ('Bank Transfer', 'Bank Transfer', NULL, 'Medium', 0.5, 600, 95.0, TRUE, FALSE, ARRAY_CONSTRUCT('US', 'CA', 'UK', 'AU', 'DE')),
    ('Cash', 'Cash', NULL, 'Low', 0.0, 0, 100.0, FALSE, TRUE, ARRAY_CONSTRUCT('US', 'CA', 'UK', 'AU'));

-- Load Channel Dimension
INSERT INTO ANALYTICS.DIM_CHANNEL (
    CHANNEL_NAME,
    CHANNEL_TYPE,
    PLATFORM_TYPE,
    DEVICE_CATEGORY,
    BROWSER_FAMILY,
    OPERATING_SYSTEM,
    IS_MOBILE,
    IS_APP,
    IS_WEB
)
VALUES
    ('Online', 'Online', 'Web', 'Desktop', 'Chrome', 'Windows', FALSE, FALSE, TRUE),
    ('Online', 'Online', 'Web', 'Desktop', 'Safari', 'macOS', FALSE, FALSE, TRUE),
    ('Online', 'Online', 'Web', 'Mobile', 'Chrome', 'Android', TRUE, FALSE, TRUE),
    ('Online', 'Online', 'Web', 'Mobile', 'Safari', 'iOS', TRUE, FALSE, TRUE),
    ('Online', 'Online', 'Web', 'Tablet', 'Safari', 'iOS', TRUE, FALSE, TRUE),
    ('Online', 'Online', 'Mobile App', 'Mobile', 'App', 'iOS', TRUE, TRUE, FALSE),
    ('Online', 'Online', 'Mobile App', 'Mobile', 'App', 'Android', TRUE, TRUE, FALSE),
    ('In-Store', 'Offline', 'In-Store', NULL, NULL, NULL, FALSE, FALSE, FALSE);

-- ============================================
-- LOAD FACT TABLES
-- ============================================

-- Load Sales Fact Table
INSERT INTO ANALYTICS.FACT_SALES (
    DATE_KEY,
    TIME_KEY,
    CUSTOMER_SK,
    PRODUCT_SK,
    STORE_SK,
    CAMPAIGN_SK,
    PAYMENT_SK,
    CHANNEL_SK,
    TRANSACTION_ID,
    ORDER_ID,
    TRANSACTION_TIMESTAMP,
    QUANTITY,
    UNIT_PRICE,
    COST_PRICE,
    LINE_DISCOUNT_AMOUNT,
    LINE_DISCOUNT_PERCENT,
    LINE_TAX_AMOUNT,
    LINE_SHIPPING_AMOUNT,
    LINE_FINAL_AMOUNT,
    TRANSACTION_SUBTOTAL,
    TRANSACTION_DISCOUNT,
    TRANSACTION_TAX,
    TRANSACTION_SHIPPING,
    TRANSACTION_TOTAL,
    PAYMENT_ID,
    PAYMENT_STATUS,
    FRAUD_DETECTED,
    FRAUD_SCORE,
    FRAUD_RISK_LEVEL,
    FULFILLMENT_STATUS,
    SHIPPING_METHOD,
    TRACKING_NUMBER,
    ESTIMATED_DELIVERY_DATE,
    ACTUAL_DELIVERY_DATE,
    DELIVERY_DAYS,
    IS_FIRST_PURCHASE,
    IS_REPEAT_PURCHASE,
    IS_CROSS_SELL,
    IS_UP_SELL,
    IS_BULK_PURCHASE,
    IS_PROMOTIONAL_ITEM,
    SESSION_ID,
    USER_AGENT,
    IP_ADDRESS,
    REFERRER_URL,
    LANDING_PAGE_URL,
    LOAD_BATCH_ID,
    SOURCE_SYSTEM
)
SELECT
    d.DATE_KEY,
    t.TIME_KEY,
    c.CUSTOMER_SK,
    p.PRODUCT_SK,
    s.STORE_SK,
    cam.CAMPAIGN_SK,
    pay.PAYMENT_SK,
    ch.CHANNEL_SK,
    st.TRANSACTION_ID,
    st.ORDER_ID,
    st.TRANSACTION_TIMESTAMP,
    ti.QUANTITY,
    ti.UNIT_PRICE,
    p.COST_PRICE,
    ti.DISCOUNT_AMOUNT,
    ti.DISCOUNT_PERCENTAGE,
    ti.TAX_AMOUNT,
    ti.FINAL_PRICE - (ti.UNIT_PRICE * ti.QUANTITY) - ti.TAX_AMOUNT AS LINE_SHIPPING_AMOUNT,
    ti.FINAL_PRICE,
    st.SUBTOTAL_AMOUNT,
    st.DISCOUNT_AMOUNT,
    st.TAX_AMOUNT,
    st.SHIPPING_AMOUNT,
    st.TOTAL_AMOUNT,
    st.PAYMENT_ID,
    st.PAYMENT_STATUS,
    st.FRAUD_DETECTED,
    st.FRAUD_SCORE,
    CASE
        WHEN st.FRAUD_SCORE > 70 THEN 'High'
        WHEN st.FRAUD_SCORE > 30 THEN 'Medium'
        ELSE 'Low'
    END AS FRAUD_RISK_LEVEL,
    st.FULFILLMENT_STATUS,
    st.SHIPPING_METHOD,
    st.TRACKING_NUMBER,
    st.ESTIMATED_DELIVERY_DATE,
    NULL AS ACTUAL_DELIVERY_DATE, -- Would come from fulfillment system
    NULL AS DELIVERY_DAYS,
    ROW_NUMBER() OVER (PARTITION BY st.CUSTOMER_ID ORDER BY st.TRANSACTION_TIMESTAMP) = 1 AS IS_FIRST_PURCHASE,
    ROW_NUMBER() OVER (PARTITION BY st.CUSTOMER_ID ORDER BY st.TRANSACTION_TIMESTAMP) > 1 AS IS_REPEAT_PURCHASE,
    FALSE AS IS_CROSS_SELL, -- Would need business logic
    FALSE AS IS_UP_SELL, -- Would need business logic
    ti.QUANTITY > 5 AS IS_BULK_PURCHASE,
    ti.DISCOUNT_PERCENTAGE > 0 AS IS_PROMOTIONAL_ITEM,
    NULL AS SESSION_ID, -- From web analytics
    st.DEVICE_TYPE || ' ' || st.BROWSER AS USER_AGENT,
    st.IP_ADDRESS,
    NULL AS REFERRER_URL, -- From web analytics
    NULL AS LANDING_PAGE_URL, -- From web analytics
    'BATCH_' || CURRENT_DATE()::STRING,
    'SALES_PLATFORM'
FROM STAGING.TRANSACTIONS st
JOIN STAGING.TRANSACTION_ITEMS ti ON st.TRANSACTION_ID = ti.TRANSACTION_ID
JOIN ANALYTICS.DIM_DATE d ON DATE(st.TRANSACTION_TIMESTAMP) = d.DATE
JOIN ANALYTICS.DIM_TIME t ON EXTRACT(HOUR FROM st.TRANSACTION_TIMESTAMP) = t.HOUR
    AND EXTRACT(MINUTE FROM st.TRANSACTION_TIMESTAMP) = t.MINUTE
JOIN ANALYTICS.DIM_CUSTOMER c ON st.CUSTOMER_ID = c.CUSTOMER_ID AND c.IS_CURRENT = TRUE
JOIN ANALYTICS.DIM_PRODUCT p ON ti.PRODUCT_ID = p.PRODUCT_ID AND p.IS_CURRENT = TRUE
LEFT JOIN ANALYTICS.DIM_STORE s ON st.STORE_ID = s.STORE_ID AND s.IS_CURRENT = TRUE
LEFT JOIN ANALYTICS.DIM_CAMPAIGN cam ON st.CAMPAIGN_ID = cam.CAMPAIGN_ID AND cam.IS_CURRENT = TRUE
JOIN ANALYTICS.DIM_PAYMENT pay ON st.PAYMENT_METHOD = pay.PAYMENT_METHOD
JOIN ANALYTICS.DIM_CHANNEL ch ON st.CHANNEL = ch.CHANNEL_NAME
    AND st.DEVICE_TYPE = ch.DEVICE_CATEGORY
WHERE st.IS_VALID = TRUE
AND st.TRANSACTION_TIMESTAMP IS NOT NULL;

-- ============================================
-- CREATE DAILY SALES SNAPSHOT
-- ============================================

INSERT INTO ANALYTICS.FACT_DAILY_SALES_SNAPSHOT (
    SNAPSHOT_DATE,
    DATE_KEY,
    CUSTOMER_SK,
    PRODUCT_SK,
    STORE_SK,
    TOTAL_TRANSACTIONS,
    TOTAL_LINE_ITEMS,
    TOTAL_QUANTITY_SOLD,
    TOTAL_CUSTOMERS,
    TOTAL_SALES_AMOUNT,
    TOTAL_DISCOUNT_AMOUNT,
    TOTAL_TAX_AMOUNT,
    TOTAL_SHIPPING_AMOUNT,
    TOTAL_NET_SALES,
    TOTAL_COST_AMOUNT,
    TOTAL_PROFIT_AMOUNT,
    AVERAGE_PROFIT_MARGIN,
    AVERAGE_TRANSACTION_VALUE,
    AVERAGE_ITEMS_PER_TRANSACTION,
    AVERAGE_ITEM_VALUE,
    NEW_CUSTOMERS_COUNT,
    REPEAT_CUSTOMERS_COUNT,
    CHURNED_CUSTOMERS_COUNT,
    TOP_SELLING_PRODUCT_ID,
    TOP_SELLING_CATEGORY,
    FRAUDULENT_TRANSACTIONS_COUNT,
    FRAUD_AMOUNT,
    FRAUD_RATE_PERCENT,
    IS_COMPLETE
)
SELECT
    DATE(fs.TRANSACTION_TIMESTAMP) AS SNAPSHOT_DATE,
    fs.DATE_KEY,
    fs.CUSTOMER_SK,
    fs.PRODUCT_SK,
    fs.STORE_SK,
    COUNT(DISTINCT fs.TRANSACTION_ID) AS TOTAL_TRANSACTIONS,
    COUNT(*) AS TOTAL_LINE_ITEMS,
    SUM(fs.QUANTITY) AS TOTAL_QUANTITY_SOLD,
    COUNT(DISTINCT fs.CUSTOMER_SK) AS TOTAL_CUSTOMERS,
    SUM(fs.LINE_FINAL_AMOUNT) AS TOTAL_SALES_AMOUNT,
    SUM(fs.LINE_DISCOUNT_AMOUNT) AS TOTAL_DISCOUNT_AMOUNT,
    SUM(fs.LINE_TAX_AMOUNT) AS TOTAL_TAX_AMOUNT,
    SUM(fs.LINE_SHIPPING_AMOUNT) AS TOTAL_SHIPPING_AMOUNT,
    SUM(fs.LINE_FINAL_AMOUNT) AS TOTAL_NET_SALES,
    SUM(fs.LINE_COST_AMOUNT) AS TOTAL_COST_AMOUNT,
    SUM(fs.LINE_PROFIT_AMOUNT) AS TOTAL_PROFIT_AMOUNT,
    AVG(fs.LINE_PROFIT_MARGIN) AS AVERAGE_PROFIT_MARGIN,
    AVG(fs.TRANSACTION_TOTAL) AS AVERAGE_TRANSACTION_VALUE,
    AVG(fs.QUANTITY) AS AVERAGE_ITEMS_PER_TRANSACTION,
    AVG(fs.UNIT_PRICE) AS AVERAGE_ITEM_VALUE,
    SUM(CASE WHEN fs.IS_FIRST_PURCHASE THEN 1 ELSE 0 END) AS NEW_CUSTOMERS_COUNT,
    SUM(CASE WHEN fs.IS_REPEAT_PURCHASE THEN 1 ELSE 0 END) AS REPEAT_CUSTOMERS_COUNT,
    0 AS CHURNED_CUSTOMERS_COUNT, -- Would need churn logic
    FIRST_VALUE(dp.PRODUCT_ID) OVER (PARTITION BY DATE(fs.TRANSACTION_TIMESTAMP), fs.PRODUCT_SK ORDER BY SUM(fs.QUANTITY) DESC) AS TOP_SELLING_PRODUCT_ID,
    FIRST_VALUE(dp.CATEGORY) OVER (PARTITION BY DATE(fs.TRANSACTION_TIMESTAMP), fs.PRODUCT_SK ORDER BY SUM(fs.QUANTITY) DESC) AS TOP_SELLING_CATEGORY,
    SUM(CASE WHEN fs.FRAUD_DETECTED THEN 1 ELSE 0 END) AS FRAUDULENT_TRANSACTIONS_COUNT,
    SUM(CASE WHEN fs.FRAUD_DETECTED THEN fs.LINE_FINAL_AMOUNT ELSE 0 END) AS FRAUD_AMOUNT,
    CASE 
        WHEN COUNT(*) > 0 THEN SUM(CASE WHEN fs.FRAUD_DETECTED THEN 1 ELSE 0 END) * 100.0 / COUNT(*) 
        ELSE 0 
    END AS FRAUD_RATE_PERCENT,
    TRUE AS IS_COMPLETE
FROM ANALYTICS.FACT_SALES fs
JOIN ANALYTICS.DIM_PRODUCT dp ON fs.PRODUCT_SK = dp.PRODUCT_SK
GROUP BY 
    DATE(fs.TRANSACTION_TIMESTAMP),
    fs.DATE_KEY,
    fs.CUSTOMER_SK,
    fs.PRODUCT_SK,
    fs.STORE_SK,
    dp.PRODUCT_ID,
    dp.CATEGORY;

-- ============================================
-- LOAD AUDIT LOGS
-- ============================================

INSERT INTO AUDIT.ETL_LOGS (
    PROCESS_NAME,
    SCHEMA_NAME,
    TABLE_NAME,
    RECORDS_PROCESSED,
    START_TIME,
    END_TIME,
    STATUS,
    ERROR_MESSAGE
)
VALUES
    ('COPY_RAW_DATA', 'RAW', 'TRANSACTIONS_RAW', (SELECT COUNT(*) FROM RAW.TRANSACTIONS_RAW), CURRENT_TIMESTAMP() - INTERVAL '5 minutes', CURRENT_TIMESTAMP(), 'SUCCESS', NULL),
    ('LOAD_STAGING', 'STAGING', 'TRANSACTIONS', (SELECT COUNT(*) FROM STAGING.TRANSACTIONS), CURRENT_TIMESTAMP() - INTERVAL '4 minutes', CURRENT_TIMESTAMP(), 'SUCCESS', NULL),
    ('LOAD_DIMENSIONS', 'ANALYTICS', 'DIM_CUSTOMER', (SELECT COUNT(*) FROM ANALYTICS.DIM_CUSTOMER), CURRENT_TIMESTAMP() - INTERVAL '3 minutes', CURRENT_TIMESTAMP(), 'SUCCESS', NULL),
    ('LOAD_FACTS', 'ANALYTICS', 'FACT_SALES', (SELECT COUNT(*) FROM ANALYTICS.FACT_SALES), CURRENT_TIMESTAMP() - INTERVAL '2 minutes', CURRENT_TIMESTAMP(), 'SUCCESS', NULL),
    ('CREATE_SNAPSHOTS', 'ANALYTICS', 'FACT_DAILY_SALES_SNAPSHOT', (SELECT COUNT(*) FROM ANALYTICS.FACT_DAILY_SALES_SNAPSHOT), CURRENT_TIMESTAMP() - INTERVAL '1 minute', CURRENT_TIMESTAMP(), 'SUCCESS', NULL);

-- ============================================
-- DATA LOADING SUMMARY
-- ============================================

SELECT
    'RAW DATA' as stage,
    TABLE_NAME,
    COUNT(*) as record_count
FROM RAW.TRANSACTIONS_RAW
GROUP BY TABLE_NAME

UNION ALL

SELECT
    'STAGING DATA',
    TABLE_NAME,
    COUNT(*)
FROM STAGING.TRANSACTIONS
GROUP BY TABLE_NAME

UNION ALL

SELECT
    'DIMENSION TABLES',
    TABLE_NAME,
    COUNT(*)
FROM ANALYTICS.DIM_CUSTOMER
GROUP BY TABLE_NAME

UNION ALL

SELECT
    'FACT TABLES',
    TABLE_NAME,
    COUNT(*)
FROM ANALYTICS.FACT_SALES
GROUP BY TABLE_NAME

ORDER BY stage, TABLE_NAME;