-- ============================================
-- CREATE RAW DATA TABLES
-- ============================================

-- Raw transactions table (landing zone)
CREATE OR REPLACE TABLE RAW.TRANSACTIONS_RAW (
    RAW_DATA VARIANT, -- Store complete JSON
    TRANSACTION_ID STRING AS (RAW_DATA:transaction_id::STRING),
    ORDER_ID STRING AS (RAW_DATA:order_id::STRING),
    TIMESTAMP TIMESTAMP_NTZ AS (RAW_DATA:timestamp::TIMESTAMP_NTZ),
    CUSTOMER_ID STRING AS (RAW_DATA:customer.customer_id::STRING),
    CUSTOMER_EMAIL STRING AS (RAW_DATA:customer.email::STRING),
    TOTAL_AMOUNT FLOAT AS (RAW_DATA:financials.total_amount::FLOAT),
    PAYMENT_METHOD STRING AS (RAW_DATA:payment.method::STRING),
    PAYMENT_STATUS STRING AS (RAW_DATA:payment.status::STRING),
    CHANNEL STRING AS (RAW_DATA:channel::STRING),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_FILE STRING,
    BATCH_ID STRING
)
CLUSTER BY (DATE(TIMESTAMP), CUSTOMER_ID)
COMMENT = 'Raw transaction data from streaming sources';

-- Raw products data
CREATE OR REPLACE TABLE RAW.PRODUCTS_RAW (
    RAW_DATA VARIANT,
    PRODUCT_ID STRING AS (RAW_DATA:product_id::STRING),
    PRODUCT_NAME STRING AS (RAW_DATA:product_name::STRING),
    CATEGORY STRING AS (RAW_DATA:category::STRING),
    PRICE FLOAT AS (RAW_DATA:price::FLOAT),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (CATEGORY, PRODUCT_ID)
COMMENT = 'Raw product catalog data';

-- Raw customers data
CREATE OR REPLACE TABLE RAW.CUSTOMERS_RAW (
    RAW_DATA VARIANT,
    CUSTOMER_ID STRING AS (RAW_DATA:customer_id::STRING),
    EMAIL STRING AS (RAW_DATA:email::STRING),
    FIRST_NAME STRING AS (RAW_DATA:first_name::STRING),
    LAST_NAME STRING AS (RAW_DATA:last_name::STRING),
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (CUSTOMER_ID)
COMMENT = 'Raw customer data';

-- ============================================
-- CREATE STAGING TABLES (TRANSFORMED DATA)
-- ============================================

-- Staging transactions (cleaned and validated)
CREATE OR REPLACE TABLE STAGING.TRANSACTIONS (
    TRANSACTION_ID STRING PRIMARY KEY,
    ORDER_ID STRING,
    TRANSACTION_TIMESTAMP TIMESTAMP_NTZ,
    CUSTOMER_ID STRING,
    STORE_ID STRING,
    CAMPAIGN_ID STRING,
    SALES_REP_ID STRING,
    CHANNEL STRING,
    DEVICE_TYPE STRING,
    BROWSER STRING,
    OS STRING,
    IP_ADDRESS STRING,
    SUBTOTAL_AMOUNT FLOAT,
    DISCOUNT_AMOUNT FLOAT,
    TAX_AMOUNT FLOAT,
    SHIPPING_AMOUNT FLOAT,
    TOTAL_AMOUNT FLOAT,
    PAYMENT_METHOD STRING,
    PAYMENT_STATUS STRING,
    PAYMENT_ID STRING,
    FRAUD_DETECTED BOOLEAN,
    FRAUD_SCORE INTEGER,
    CURRENCY STRING,
    FULFILLMENT_STATUS STRING,
    SHIPPING_METHOD STRING,
    TRACKING_NUMBER STRING,
    ESTIMATED_DELIVERY_DATE DATE,
    SEASON STRING,
    IS_WEEKEND BOOLEAN,
    IS_HOLIDAY BOOLEAN,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID STRING,
    IS_VALID BOOLEAN DEFAULT TRUE,
    VALIDATION_ERRORS STRING
)
CLUSTER BY (DATE(TRANSACTION_TIMESTAMP), CUSTOMER_ID)
COMMENT = 'Cleaned and validated transaction data';

-- Staging transaction items (line items)
CREATE OR REPLACE TABLE STAGING.TRANSACTION_ITEMS (
    TRANSACTION_ITEM_ID STRING DEFAULT UUID_STRING() PRIMARY KEY,
    TRANSACTION_ID STRING,
    PRODUCT_ID STRING,
    QUANTITY INTEGER,
    UNIT_PRICE FLOAT,
    TOTAL_PRICE FLOAT,
    DISCOUNT_PERCENTAGE FLOAT,
    DISCOUNT_AMOUNT FLOAT,
    TAX_AMOUNT FLOAT,
    FINAL_PRICE FLOAT,
    PRODUCT_CATEGORY STRING,
    PRODUCT_SUBCATEGORY STRING,
    PRODUCT_BRAND STRING,
    PRODUCT_SKU STRING,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (TRANSACTION_ID, PRODUCT_ID)
COMMENT = 'Transaction line items';

-- Staging customers
CREATE OR REPLACE TABLE STAGING.CUSTOMERS (
    CUSTOMER_ID STRING PRIMARY KEY,
    FIRST_NAME STRING,
    LAST_NAME STRING,
    EMAIL STRING,
    PHONE_NUMBER STRING,
    DATE_OF_BIRTH DATE,
    AGE INTEGER,
    GENDER STRING,
    INCOME_BRACKET STRING,
    OCCUPATION STRING,
    COMPANY STRING,
    ADDRESS_STREET STRING,
    ADDRESS_CITY STRING,
    ADDRESS_STATE STRING,
    ADDRESS_COUNTRY STRING,
    ADDRESS_POSTAL_CODE STRING,
    ADDRESS_REGION STRING,
    ACCOUNT_CREATED_DATE DATE,
    LAST_LOGIN_DATE DATE,
    ACCOUNT_STATUS STRING,
    CUSTOMER_SEGMENT STRING,
    LIFETIME_VALUE FLOAT,
    AVG_ORDER_VALUE FLOAT,
    PURCHASE_FREQUENCY FLOAT,
    LAST_PURCHASE_DATE DATE,
    TOTAL_ORDERS INTEGER,
    TOTAL_SPENT FLOAT,
    PREFERRED_CHANNEL STRING,
    PREFERRED_CATEGORY STRING,
    LOYALTY_POINTS INTEGER,
    NEWSLETTER_SUBSCRIBED BOOLEAN,
    MARKETING_OPT_IN BOOLEAN,
    CUSTOMER_TIER STRING,
    CREDIT_SCORE INTEGER,
    PREFERRED_PAYMENT_METHOD STRING,
    SHIPPING_PREFERENCE STRING,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_ACTIVE BOOLEAN DEFAULT TRUE
)
CLUSTER BY (CUSTOMER_SEGMENT, CUSTOMER_TIER)
COMMENT = 'Cleaned customer data';

-- Staging products
CREATE OR REPLACE TABLE STAGING.PRODUCTS (
    PRODUCT_ID STRING PRIMARY KEY,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    SUBCATEGORY STRING,
    BRAND STRING,
    SKU STRING,
    PRICE FLOAT,
    COST_PRICE FLOAT,
    PROFIT_MARGIN FLOAT,
    STOCK_QUANTITY INTEGER,
    REORDER_LEVEL INTEGER,
    SUPPLIER_ID STRING,
    MANUFACTURER STRING,
    WEIGHT_KG FLOAT,
    DIMENSIONS STRING,
    COLOR STRING,
    MATERIAL STRING,
    WARRANTY_MONTHS INTEGER,
    RATING FLOAT,
    REVIEWS_COUNT INTEGER,
    IS_ACTIVE BOOLEAN,
    DATE_ADDED DATE,
    LAST_UPDATED TIMESTAMP_NTZ,
    TAGS ARRAY,
    DESCRIPTION STRING,
    FEATURES ARRAY,
    IS_SEASONAL BOOLEAN,
    IS_LIMITED_EDITION BOOLEAN,
    IS_BESTSELLER BOOLEAN,
    IS_NEW_ARRIVAL BOOLEAN,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (CATEGORY, SUBCATEGORY, BRAND)
COMMENT = 'Cleaned product catalog';

-- Staging stores
CREATE OR REPLACE TABLE STAGING.STORES (
    STORE_ID STRING PRIMARY KEY,
    STORE_NAME STRING,
    STORE_TYPE STRING,
    FORMAT STRING,
    ADDRESS_STREET STRING,
    ADDRESS_CITY STRING,
    ADDRESS_STATE STRING,
    ADDRESS_COUNTRY STRING,
    ADDRESS_POSTAL_CODE STRING,
    ADDRESS_REGION STRING,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    PHONE_NUMBER STRING,
    EMAIL STRING,
    MANAGER_ID STRING,
    OPENING_DATE DATE,
    SIZE_SQFT INTEGER,
    EMPLOYEE_COUNT INTEGER,
    AVG_DAILY_CUSTOMERS INTEGER,
    AVG_TRANSACTION_VALUE FLOAT,
    MONTHLY_SALES FLOAT,
    INVENTORY_VALUE FLOAT,
    PARKING_SPACES INTEGER,
    HAS_CAFE BOOLEAN,
    HAS_WIFI BOOLEAN,
    IS_24_HOURS BOOLEAN,
    LAST_RENOVATION_DATE DATE,
    STATUS STRING,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (ADDRESS_REGION, STORE_TYPE)
COMMENT = 'Store location information';

-- Staging campaigns
CREATE OR REPLACE TABLE STAGING.CAMPAIGNS (
    CAMPAIGN_ID STRING PRIMARY KEY,
    CAMPAIGN_NAME STRING,
    CAMPAIGN_TYPE STRING,
    CHANNEL STRING,
    STATUS STRING,
    START_DATE DATE,
    END_DATE DATE,
    TARGET_AUDIENCE STRING,
    TARGET_SEGMENT STRING,
    OBJECTIVE STRING,
    BUDGET FLOAT,
    SPENT FLOAT,
    REMAINING_BUDGET FLOAT,
    IMPRESSIONS INTEGER,
    CLICKS INTEGER,
    CONVERSIONS INTEGER,
    REVENUE FLOAT,
    CTR FLOAT,
    CONVERSION_RATE FLOAT,
    CPC FLOAT,
    CPA FLOAT,
    ROAS FLOAT,
    TEAM_LEAD STRING,
    AGENCY STRING,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (CAMPAIGN_TYPE, STATUS)
COMMENT = 'Marketing campaign data';

-- ============================================
-- CREATE ANALYTICS SCHEMA TABLES (STAR SCHEMA)
-- ============================================

-- DATE DIMENSION
CREATE OR REPLACE TABLE ANALYTICS.DIM_DATE (
    DATE_KEY INTEGER PRIMARY KEY, -- YYYYMMDD format
    DATE DATE NOT NULL,
    YEAR INTEGER NOT NULL,
    QUARTER INTEGER NOT NULL,
    MONTH INTEGER NOT NULL,
    MONTH_NAME STRING NOT NULL,
    DAY_OF_MONTH INTEGER NOT NULL,
    DAY_OF_WEEK INTEGER NOT NULL,
    DAY_NAME STRING NOT NULL,
    WEEK_OF_YEAR INTEGER NOT NULL,
    IS_WEEKEND BOOLEAN NOT NULL,
    IS_HOLIDAY BOOLEAN NOT NULL,
    HOLIDAY_NAME STRING,
    FISCAL_YEAR INTEGER NOT NULL,
    FISCAL_QUARTER INTEGER NOT NULL,
    FISCAL_MONTH INTEGER NOT NULL,
    SEASON STRING NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Date dimension table for time-based analysis';

-- TIME DIMENSION
CREATE OR REPLACE TABLE ANALYTICS.DIM_TIME (
    TIME_KEY INTEGER PRIMARY KEY, -- HHMM format
    HOUR INTEGER NOT NULL,
    MINUTE INTEGER NOT NULL,
    HOUR_OF_DAY INTEGER NOT NULL,
    TIME_PERIOD STRING NOT NULL, -- Morning, Afternoon, Evening, Night
    IS_BUSINESS_HOURS BOOLEAN NOT NULL,
    IS_PEAK_HOURS BOOLEAN NOT NULL,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
COMMENT = 'Time dimension table for hourly analysis';

-- CUSTOMER DIMENSION
CREATE OR REPLACE TABLE ANALYTICS.DIM_CUSTOMER (
    CUSTOMER_SK INTEGER DEFAULT ANALYTICS.DIM_CUSTOMER_SEQ.NEXTVAL PRIMARY KEY,
    CUSTOMER_ID STRING NOT NULL,
    CUSTOMER_NAME STRING,
    EMAIL STRING,
    PHONE_NUMBER STRING,
    DATE_OF_BIRTH DATE,
    AGE INTEGER,
    AGE_GROUP STRING,
    GENDER STRING,
    INCOME_BRACKET STRING,
    OCCUPATION STRING,
    COMPANY STRING,
    CITY STRING,
    STATE STRING,
    COUNTRY STRING,
    REGION STRING,
    POSTAL_CODE STRING,
    ACCOUNT_CREATED_DATE DATE,
    ACCOUNT_AGE_DAYS INTEGER,
    ACCOUNT_STATUS STRING,
    CUSTOMER_SEGMENT STRING,
    CUSTOMER_TIER STRING,
    LIFETIME_VALUE DECIMAL(15,2),
    VALUE_SEGMENT STRING, -- High, Medium, Low value
    PURCHASE_FREQUENCY FLOAT,
    FREQUENCY_SEGMENT STRING, -- Frequent, Regular, Occasional
    RECENCY_DAYS INTEGER,
    RECENCY_SEGMENT STRING, -- Recent, Active, Lapsed, Churned
    RFM_SCORE INTEGER,
    RFM_SEGMENT STRING,
    PREFERRED_CHANNEL STRING,
    PREFERRED_CATEGORY STRING,
    LOYALTY_POINTS INTEGER,
    NEWSLETTER_SUBSCRIBED BOOLEAN,
    MARKETING_OPT_IN BOOLEAN,
    CREDIT_SCORE INTEGER,
    PREFERRED_PAYMENT_METHOD STRING,
    SHIPPING_PREFERENCE STRING,
    IS_ACTIVE BOOLEAN,
    VALID_FROM TIMESTAMP_NTZ NOT NULL,
    VALID_TO TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (CUSTOMER_SEGMENT, CUSTOMER_TIER, REGION)
COMMENT = 'Customer dimension with SCD Type 2 for historical tracking';

-- PRODUCT DIMENSION
CREATE OR REPLACE TABLE ANALYTICS.DIM_PRODUCT (
    PRODUCT_SK INTEGER DEFAULT ANALYTICS.DIM_PRODUCT_SEQ.NEXTVAL PRIMARY KEY,
    PRODUCT_ID STRING NOT NULL,
    PRODUCT_NAME STRING NOT NULL,
    CATEGORY STRING NOT NULL,
    SUBCATEGORY STRING NOT NULL,
    BRAND STRING NOT NULL,
    SKU STRING,
    CURRENT_PRICE DECIMAL(10,2),
    COST_PRICE DECIMAL(10,2),
    PROFIT_MARGIN_PERCENT DECIMAL(5,2),
    PROFITABILITY_SEGMENT STRING, -- High, Medium, Low margin
    STOCK_QUANTITY INTEGER,
    STOCK_STATUS STRING, -- In Stock, Low Stock, Out of Stock
    SUPPLIER_ID STRING,
    MANUFACTURER STRING,
    WEIGHT_KG FLOAT,
    DIMENSIONS STRING,
    COLOR STRING,
    MATERIAL STRING,
    WARRANTY_MONTHS INTEGER,
    RATING FLOAT,
    REVIEWS_COUNT INTEGER,
    POPULARITY_SCORE INTEGER,
    PRODUCT_LIFECYCLE_STAGE STRING, -- Introduction, Growth, Maturity, Decline
    IS_ACTIVE BOOLEAN,
    IS_SEASONAL BOOLEAN,
    IS_LIMITED_EDITION BOOLEAN,
    IS_BESTSELLER BOOLEAN,
    IS_NEW_ARRIVAL BOOLEAN,
    DATE_ADDED DATE,
    VALID_FROM TIMESTAMP_NTZ NOT NULL,
    VALID_TO TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (CATEGORY, SUBCATEGORY, BRAND)
COMMENT = 'Product dimension with SCD Type 2 for price/attribute changes';

-- STORE DIMENSION
CREATE OR REPLACE TABLE ANALYTICS.DIM_STORE (
    STORE_SK INTEGER PRIMARY KEY,
    STORE_ID STRING NOT NULL,
    STORE_NAME STRING NOT NULL,
    STORE_TYPE STRING,
    FORMAT STRING,
    CITY STRING,
    STATE STRING,
    COUNTRY STRING,
    REGION STRING,
    POSTAL_CODE STRING,
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    GEOHASH STRING,
    AREA_TYPE STRING, -- Urban, Suburban, Rural
    STORE_SIZE_SQFT INTEGER,
    SIZE_CATEGORY STRING, -- Small, Medium, Large
    EMPLOYEE_COUNT INTEGER,
    STORE_AGE_YEARS INTEGER,
    LAST_RENOVATION_YEAR INTEGER,
    HAS_CAFE BOOLEAN,
    HAS_WIFI BOOLEAN,
    IS_24_HOURS BOOLEAN,
    PARKING_CAPACITY INTEGER,
    STORE_STATUS STRING,
    PERFORMANCE_TIER STRING, -- High, Medium, Low performing
    AVG_DAILY_CUSTOMERS INTEGER,
    AVG_TRANSACTION_VALUE DECIMAL(10,2),
    IS_ACTIVE BOOLEAN,
    VALID_FROM TIMESTAMP_NTZ NOT NULL,
    VALID_TO TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (REGION, STORE_TYPE, PERFORMANCE_TIER)
COMMENT = 'Store dimension with geographical and performance attributes';

-- CAMPAIGN DIMENSION
CREATE OR REPLACE TABLE ANALYTICS.DIM_CAMPAIGN (
    CAMPAIGN_SK INTEGER PRIMARY KEY,
    CAMPAIGN_ID STRING NOT NULL,
    CAMPAIGN_NAME STRING NOT NULL,
    CAMPAIGN_TYPE STRING,
    CHANNEL STRING,
    STATUS STRING,
    START_DATE DATE,
    END_DATE DATE,
    DURATION_DAYS INTEGER,
    TARGET_AUDIENCE STRING,
    TARGET_SEGMENT STRING,
    OBJECTIVE STRING,
    BUDGET DECIMAL(15,2),
    BUDGET_SIZE_CATEGORY STRING, -- Small, Medium, Large
    TEAM_LEAD STRING,
    AGENCY STRING,
    CREATIVE_COUNT INTEGER,
    IS_ACTIVE BOOLEAN,
    VALID_FROM TIMESTAMP_NTZ NOT NULL,
    VALID_TO TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (CAMPAIGN_TYPE, CHANNEL, STATUS)
COMMENT = 'Campaign dimension for marketing attribution';

-- PAYMENT DIMENSION
CREATE OR REPLACE TABLE ANALYTICS.DIM_PAYMENT (
    PAYMENT_SK INTEGER PRIMARY KEY,
    PAYMENT_METHOD STRING NOT NULL,
    PAYMENT_TYPE STRING, -- Card, Digital Wallet, Bank Transfer, Cash
    PAYMENT_NETWORK STRING, -- Visa, Mastercard, etc.
    SECURITY_LEVEL STRING, -- High, Medium, Low
    PROCESSING_FEE_PERCENT DECIMAL(5,2),
    AVERAGE_PROCESSING_TIME_SECONDS INTEGER,
    SUCCESS_RATE_PERCENT DECIMAL(5,2),
    IS_DIGITAL BOOLEAN,
    IS_INSTANT BOOLEAN,
    SUPPORTED_COUNTRIES ARRAY,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (PAYMENT_TYPE, PAYMENT_METHOD)
COMMENT = 'Payment method dimension';

-- CHANNEL DIMENSION
CREATE OR REPLACE TABLE ANALYTICS.DIM_CHANNEL (
    CHANNEL_SK INTEGER PRIMARY KEY,
    CHANNEL_NAME STRING NOT NULL,
    CHANNEL_TYPE STRING, -- Online, Offline, Hybrid
    PLATFORM_TYPE STRING, -- Web, Mobile, In-Store
    DEVICE_CATEGORY STRING, -- Desktop, Mobile, Tablet
    BROWSER_FAMILY STRING,
    OPERATING_SYSTEM STRING,
    IS_MOBILE BOOLEAN,
    IS_APP BOOLEAN,
    IS_WEB BOOLEAN,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (CHANNEL_TYPE, PLATFORM_TYPE)
COMMENT = 'Sales channel dimension';

-- ============================================
-- CREATE FACT TABLES
-- ============================================

-- SALES FACT TABLE (GRAIN: Transaction Line Item)
CREATE OR REPLACE TABLE ANALYTICS.FACT_SALES (
    SALES_SK INTEGER DEFAULT ANALYTICS.FACT_SALES_SEQ.NEXTVAL PRIMARY KEY,
    DATE_KEY INTEGER REFERENCES ANALYTICS.DIM_DATE(DATE_KEY),
    TIME_KEY INTEGER REFERENCES ANALYTICS.DIM_TIME(TIME_KEY),
    CUSTOMER_SK INTEGER REFERENCES ANALYTICS.DIM_CUSTOMER(CUSTOMER_SK),
    PRODUCT_SK INTEGER REFERENCES ANALYTICS.DIM_PRODUCT(PRODUCT_SK),
    STORE_SK INTEGER REFERENCES ANALYTICS.DIM_STORE(STORE_SK),
    CAMPAIGN_SK INTEGER REFERENCES ANALYTICS.DIM_CAMPAIGN(CAMPAIGN_SK),
    PAYMENT_SK INTEGER REFERENCES ANALYTICS.DIM_PAYMENT(PAYMENT_SK),
    CHANNEL_SK INTEGER REFERENCES ANALYTICS.DIM_CHANNEL(CHANNEL_SK),
    
    -- Transaction Details
    TRANSACTION_ID STRING NOT NULL,
    ORDER_ID STRING NOT NULL,
    TRANSACTION_TIMESTAMP TIMESTAMP_NTZ NOT NULL,
    
    -- Product Details
    QUANTITY INTEGER NOT NULL,
    UNIT_PRICE DECIMAL(10,2) NOT NULL,
    COST_PRICE DECIMAL(10,2),
    
    -- Financial Metrics
    LINE_TOTAL_AMOUNT DECIMAL(15,2) AS (QUANTITY * UNIT_PRICE),
    LINE_DISCOUNT_AMOUNT DECIMAL(15,2),
    LINE_DISCOUNT_PERCENT DECIMAL(5,2),
    LINE_TAX_AMOUNT DECIMAL(15,2),
    LINE_SHIPPING_AMOUNT DECIMAL(15,2),
    LINE_FINAL_AMOUNT DECIMAL(15,2),
    
    -- Transaction Level Aggregates (for consistency)
    TRANSACTION_SUBTOTAL DECIMAL(15,2),
    TRANSACTION_DISCOUNT DECIMAL(15,2),
    TRANSACTION_TAX DECIMAL(15,2),
    TRANSACTION_SHIPPING DECIMAL(15,2),
    TRANSACTION_TOTAL DECIMAL(15,2),
    
    -- Profit Metrics
    LINE_COST_AMOUNT DECIMAL(15,2) AS (QUANTITY * COST_PRICE),
    LINE_PROFIT_AMOUNT DECIMAL(15,2) AS (LINE_FINAL_AMOUNT - LINE_COST_AMOUNT),
    LINE_PROFIT_MARGIN DECIMAL(5,2) AS (CASE WHEN LINE_FINAL_AMOUNT > 0 THEN (LINE_PROFIT_AMOUNT / LINE_FINAL_AMOUNT) * 100 ELSE 0 END),
    
    -- Payment Details
    PAYMENT_ID STRING,
    PAYMENT_STATUS STRING,
    FRAUD_DETECTED BOOLEAN,
    FRAUD_SCORE INTEGER,
    FRAUD_RISK_LEVEL STRING, -- Low, Medium, High
    
    -- Fulfillment Details
    FULFILLMENT_STATUS STRING,
    SHIPPING_METHOD STRING,
    TRACKING_NUMBER STRING,
    ESTIMATED_DELIVERY_DATE DATE,
    ACTUAL_DELIVERY_DATE DATE,
    DELIVERY_DAYS INTEGER,
    
    -- Business Context
    IS_FIRST_PURCHASE BOOLEAN,
    IS_REPEAT_PURCHASE BOOLEAN,
    IS_CROSS_SELL BOOLEAN,
    IS_UP_SELL BOOLEAN,
    IS_BULK_PURCHASE BOOLEAN,
    IS_PROMOTIONAL_ITEM BOOLEAN,
    
    -- Session Details (for online)
    SESSION_ID STRING,
    USER_AGENT STRING,
    IP_ADDRESS STRING,
    REFERRER_URL STRING,
    LANDING_PAGE_URL STRING,
    
    -- Audit Fields
    LOAD_BATCH_ID STRING,
    SOURCE_SYSTEM STRING,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (DATE_KEY, CUSTOMER_SK, PRODUCT_SK)
COMMENT = 'Sales fact table at transaction line item granularity';

-- DAILY SALES SNAPSHOT (AGGREGATED)
CREATE OR REPLACE TABLE ANALYTICS.FACT_DAILY_SALES_SNAPSHOT (
    SNAPSHOT_DATE DATE NOT NULL,
    DATE_KEY INTEGER REFERENCES ANALYTICS.DIM_DATE(DATE_KEY),
    CUSTOMER_SK INTEGER REFERENCES ANALYTICS.DIM_CUSTOMER(CUSTOMER_SK),
    PRODUCT_SK INTEGER REFERENCES ANALYTICS.DIM_PRODUCT(PRODUCT_SK),
    STORE_SK INTEGER REFERENCES ANALYTICS.DIM_STORE(STORE_SK),
    
    -- Daily Aggregates
    TOTAL_TRANSACTIONS INTEGER,
    TOTAL_LINE_ITEMS INTEGER,
    TOTAL_QUANTITY_SOLD INTEGER,
    TOTAL_CUSTOMERS INTEGER,
    
    -- Financial Aggregates
    TOTAL_SALES_AMOUNT DECIMAL(15,2),
    TOTAL_DISCOUNT_AMOUNT DECIMAL(15,2),
    TOTAL_TAX_AMOUNT DECIMAL(15,2),
    TOTAL_SHIPPING_AMOUNT DECIMAL(15,2),
    TOTAL_NET_SALES DECIMAL(15,2),
    TOTAL_COST_AMOUNT DECIMAL(15,2),
    TOTAL_PROFIT_AMOUNT DECIMAL(15,2),
    AVERAGE_PROFIT_MARGIN DECIMAL(5,2),
    
    -- Averages
    AVERAGE_TRANSACTION_VALUE DECIMAL(10,2),
    AVERAGE_ITEMS_PER_TRANSACTION DECIMAL(5,2),
    AVERAGE_ITEM_VALUE DECIMAL(10,2),
    
    -- Customer Metrics
    NEW_CUSTOMERS_COUNT INTEGER,
    REPEAT_CUSTOMERS_COUNT INTEGER,
    CHURNED_CUSTOMERS_COUNT INTEGER,
    
    -- Product Metrics
    TOP_SELLING_PRODUCT_ID STRING,
    TOP_SELLING_CATEGORY STRING,
    
    -- Fraud Metrics
    FRAUDULENT_TRANSACTIONS_COUNT INTEGER,
    FRAUD_AMOUNT DECIMAL(15,2),
    FRAUD_RATE_PERCENT DECIMAL(5,2),
    
    -- Load Metadata
    SNAPSHOT_LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    IS_COMPLETE BOOLEAN DEFAULT FALSE,
    
    PRIMARY KEY (SNAPSHOT_DATE, CUSTOMER_SK, PRODUCT_SK, STORE_SK)
)
CLUSTER BY (SNAPSHOT_DATE, PRODUCT_SK)
COMMENT = 'Daily aggregated sales snapshot for fast reporting';

-- ============================================
-- CREATE INVENTORY FACT TABLE
-- ============================================

CREATE OR REPLACE TABLE ANALYTICS.FACT_INVENTORY (
    INVENTORY_SK INTEGER PRIMARY KEY,
    DATE_KEY INTEGER REFERENCES ANALYTICS.DIM_DATE(DATE_KEY),
    PRODUCT_SK INTEGER REFERENCES ANALYTICS.DIM_PRODUCT(PRODUCT_SK),
    STORE_SK INTEGER REFERENCES ANALYTICS.DIM_STORE(STORE_SK),
    
    -- Inventory Levels
    OPENING_STOCK INTEGER,
    RECEIVED_QUANTITY INTEGER,
    SOLD_QUANTITY INTEGER,
    RETURNED_QUANTITY INTEGER,
    DAMAGED_QUANTITY INTEGER,
    ADJUSTED_QUANTITY INTEGER,
    CLOSING_STOCK INTEGER,
    
    -- Stock Metrics
    DAYS_OF_SUPPLY INTEGER,
    STOCK_OUT_DAYS INTEGER,
    STOCK_COVERAGE_RATIO DECIMAL(5,2),
    
    -- Sales Metrics
    FORECASTED_DEMAND INTEGER,
    ACTUAL_DEMAND INTEGER,
    FORECAST_ACCURACY_PERCENT DECIMAL(5,2),
    
    -- Reorder Information
    REORDER_POINT INTEGER,
    REORDER_QUANTITY INTEGER,
    REORDER_STATUS STRING, -- Ordered, In Transit, Received
    
    -- Financial Impact
    STOCK_VALUE DECIMAL(15,2),
    STOCK_OUT_COST DECIMAL(15,2),
    HOLDING_COST DECIMAL(15,2),
    
    -- Audit
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE_SYSTEM STRING
)
CLUSTER BY (DATE_KEY, PRODUCT_SK, STORE_SK)
COMMENT = 'Daily inventory facts for stock management';

-- ============================================
-- CREATE MARKETING FACT TABLE
-- ============================================

CREATE OR REPLACE TABLE ANALYTICS.FACT_MARKETING_PERFORMANCE (
    MARKETING_SK INTEGER PRIMARY KEY,
    DATE_KEY INTEGER REFERENCES ANALYTICS.DIM_DATE(DATE_KEY),
    CAMPAIGN_SK INTEGER REFERENCES ANALYTICS.DIM_CAMPAIGN(CAMPAIGN_SK),
    CHANNEL_SK INTEGER REFERENCES ANALYTICS.DIM_CHANNEL(CHANNEL_SK),
    
    -- Campaign Performance Metrics
    IMPRESSIONS INTEGER,
    CLICKS INTEGER,
    CONVERSIONS INTEGER,
    LEADS_GENERATED INTEGER,
    QUALIFIED_LEADS INTEGER,
    
    -- Financial Metrics
    SPEND_AMOUNT DECIMAL(15,2),
    REVENUE_ATTRIBUTED DECIMAL(15,2),
    COST_PER_IMPRESSION DECIMAL(10,4),
    COST_PER_CLICK DECIMAL(10,2),
    COST_PER_ACQUISITION DECIMAL(10,2),
    
    -- Engagement Metrics
    CLICK_THROUGH_RATE_PERCENT DECIMAL(5,2),
    CONVERSION_RATE_PERCENT DECIMAL(5,2),
    BOUNCE_RATE_PERCENT DECIMAL(5,2),
    AVG_SESSION_DURATION_SECONDS INTEGER,
    
    -- ROI Metrics
    RETURN_ON_AD_SPEND DECIMAL(10,2),
    CUSTOMER_LIFETIME_VALUE DECIMAL(15,2),
    PAYBACK_PERIOD_DAYS INTEGER,
    
    -- Attribution
    ATTRIBUTION_MODEL STRING,
    FIRST_TOUCH_CONTRIBUTION DECIMAL(5,2),
    LAST_TOUCH_CONTRIBUTION DECIMAL(5,2),
    LINEAR_CONTRIBUTION DECIMAL(5,2),
    
    -- Load Metadata
    REPORTING_DATE DATE,
    LOAD_TIMESTAMP TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY (DATE_KEY, CAMPAIGN_SK, CHANNEL_SK)
COMMENT = 'Marketing campaign performance facts';

-- ============================================
-- CREATE TABLE SUMMARY
-- ============================================

SELECT
    'RAW SCHEMA' as schema_name,
    TABLE_NAME,
    ROW_COUNT,
    BYTES,
    COMMENT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'RAW' AND TABLE_CATALOG = 'SALES_DB'

UNION ALL

SELECT
    'STAGING SCHEMA',
    TABLE_NAME,
    ROW_COUNT,
    BYTES,
    COMMENT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'STAGING' AND TABLE_CATALOG = 'SALES_DB'

UNION ALL

SELECT
    'ANALYTICS SCHEMA',
    TABLE_NAME,
    ROW_COUNT,
    BYTES,
    COMMENT
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'ANALYTICS' AND TABLE_CATALOG = 'SALES_DB'

ORDER BY schema_name, TABLE_NAME;